### ISSUE TITLE
Firebase Database Complex Querying Returning Incorrect Result

### ISSUE THREAD

**Issue by troy21688** [firebase/FirebaseUI-Android#1040]
I have a Firebase Database that essentially looks like the following:

[![enter image description here][1]][1]

Ultimately, I am trying to capture "Trending" information. "Trending" would constitute:

1. Recent (When it was added to Firebase)
2. Highly Regarded (Highest Vote Count)

I am using the FirebaseUI (latest version 3.0.1) with my database. I have my query as the following:

        Query query = FirebaseDatabase.getInstance()
                .getReference()
                .child("Polls")
                .limitToLast(3)
                .orderByChild("vote_count");

The hope is to first see the most recently added children, and then order those children by the vote_count child. Unfortunately, this query is not handling correctly, as it is ordering by child first and THEN limiting to 3.

Is my query possible? Would an update to the Cloud Firestore resolve?

  [1]: https://i.stack.imgur.com/f0OeO.png

**Comment by puf** [comment]
This is unrelated to FirebaseUI, and really should be posted on Stack Overflow.

That said: the answer there will be that this cannot be done in just a Firebase Database query, since those can only order/filter on a single property. In fact, I also don't think it can be accomplished with Firestore queries. 

Your best option is to filter by recency in the query, and then reorder by vote-count in your client code.

Also see my answer here: http://stackoverflow.com/questions/26700924/query-based-on-multiple-where-clauses-in-firebase

**Comment by troy21688** [comment]
Frank -

I am a bit confused - if I am using the Firebase UI, I am bound within the limitations of the query / options I inject into the adapter. Can you further elaborate on how I would accomplish my presentation through client-side changes? I did read your post, but it is still unclear.

**Comment by puf** [comment]
Firebase Database queries can only order/filter on a single property. Since FirebaseUI is built on top of the Firebase SDK, it doesn't have any way to work around this or improve it.

You're trying to filter on multiple properties, so will need one of the approaches in the answer I linked. Given your use-case I'd recommend filtering for recency in your query, and then order by vote-count client side.

I don't think any option for re-ordering has been added into FirebaseUI, since it'd significantly change the way the mapping works. This means you'll likely need to build a custom adapter, although you can use the ones from FirebaseUI for inspiration.
