### ISSUE TITLE
Crash in LruCache when called from BaseCachingSnapshotParser.java:36

### ISSUE THREAD

**Issue by dimipaun** [firebase/FirebaseUI-Android#1105]
I keep seeing this issue in Crashlytics:
`Exception java.lang.NullPointerException: key == null || value == null
android.util.LruCache.put (LruCache.java:166)
com.firebase.ui.common.a.a (BaseCachingSnapshotParser.java:36)
com.firebase.ui.common.c.get (BaseObservableSnapshotArray.java:52)
com.firebase.ui.database.FirebaseRecyclerAdapter.a (FirebaseRecyclerAdapter.java:106)
co.edgeapp.android.ui.BaseRecyclerAdapter.onBindViewHolder (BaseRecyclerAdapter.java:109)
android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder (RecyclerView.java:6508)
android.support.v7.widget.RecyclerView$Adapter.bindViewHolder (RecyclerView.java:6541)
android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline (RecyclerView.java:5484)
android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline (RecyclerView.java:5750)
android.support.v7.widget.RecyclerView$Recycler.getViewForPosition (RecyclerView.java:5589)
android.support.v7.widget.RecyclerView$Recycler.getViewForPosition (RecyclerView.java:5585)
android.support.v7.widget.LinearLayoutManager$b.a (LinearLayoutManager.java:2231)`

I have no idea how to trigger it, but it does happen regularly (with all versions of Firebase UI (running 3.1.3 now).

**Comment by SUPERCILEX** [comment]
It means you're returning null in your `parseSnapshot` method.

**Comment by samtstern** [comment]
@SUPERCILEX is this something we should support?  Do we document the restriction?

**Comment by SUPERCILEX** [comment]
@samtstern I believe we've never supported nulls since the kind of queries we use aren't on specific refs (which means we only get docs that exist). And no, this isn't documented other than the `@NonNull` annotations. What do you think we should do? I personally don't see how returning a null model makes sense since it would require using some default model to display the nulls in the recycler view.

**Comment by samtstern** [comment]
Ok just wanted to check.

@dimipaun the answer is to not return `null` from your `SnapshotParser`.  If you think this is something we're doing please comment and I will re-open.

**Comment by dimipaun** [comment]
@SUPERCILEX @samedson I've looked at our code, and I *really* need to be able to return null. 
The reason is that our SnapshotParser can detected invalid data, in which case there's no decent value that we can return, but null.
As for the recycler view, we just don't display those rows, and frankly it is the only clean way to handle this. 
Returning a empty object is ugly & unnecessary - I really think we should be allowed to return null here.

**Comment by SUPERCILEX** [comment]
@dimipaun what do you mean by "errors"? Shouldn't you be checking that in your rules or at input time? As for returning an empty object, that's not too hard in Java:
```java
public static final EMPTY_OBJECT = new ...;
```
Then you just check if the model is the exact instance of that empty object.

The main issue with supporting nulls is that it will break everyone using Kotlin and make things extremely unpleasant. It'll also make caching harder and degrade performance in the recyclerview if you're inflating 0dp views.

**Comment by dimipaun** [comment]
@SUPERCILEX yes, we are checking in rules, but in practice the rules don't catch everything (they are always behind the times), and we can't afford to crash the app when things go wrong. 

What I'm saying is there are few cases (in terms of frequency) where the most natural thing to do is to return null. 

Of course we could return an empty object, but that is a very ugly solution especially when dealing with generics. It could be done of course, but it's ugly and unnecessary.

As for performance in recycler view, that's an issue only if there are lots of such objects. And returning an empty object doesn't really solve this issue at all, we'd still have to inflate a 0dp view.

At a conceptual level, it seems strange to have something that's supposed to parse an object not being able to say it can't do so properly.

**Comment by SUPERCILEX** [comment]
@dimipaun Hmmm, I do see your point about it feeling right to return null, but the issue on our side then becomes how do we display those nulls? I personally don't think it's acceptable for the library let nulls end up in `onBindViewHolder` so that means we'd have to do some sort of item shifting and duplication. We've been doing that in [`FirebaseIndexArray`](https://github.com/firebase/FirebaseUI-Android/blob/7ca207e6aa2654f5afe76dbee12c3b6592996046/database/src/main/java/com/firebase/ui/database/FirebaseIndexArray.java) and it's become its own tasty slice of hell (so not something I'd like to repeat).

The advantage of this code being on GitHub and not in a secret Google vault is that it's open-source! 😜 Since you're the first to request this and I'd rather not encourage using nulls for everyone else, I think your best course of action is to make a fork and implement the required changes there. @samtstern Do you think that's reasonable?

If you do make a fork, it's ridiculously easy to publish stuff on [JitPack](https://jitpack.io/) for quick development. All you need is some fake `google-services.json` (feel free to copy [mine](https://github.com/SUPERCILEX/FirebaseUI-Android/blob/fa824262ab5b6fd2bda66d24ec81beece8a0efb3/app/google-services.json)) and you're good to go. As for changes, you'll want to update [caching](https://github.com/firebase/FirebaseUI-Android/blob/7ca207e6aa2654f5afe76dbee12c3b6592996046/common/src/main/java/com/firebase/ui/common/BaseCachingSnapshotParser.java#L36) and implement either some sort of list shifting in the adapter or apply a transformtion to the `FirestoreArray` and then recompute the diff using [`DiffUtil`](https://developer.android.com/reference/android/support/v7/util/DiffUtil.html).

**Comment by dimipaun** [comment]
@SUPERCILEX thanks for the suggestion. I've actually went ahead and did the empty object, it is indeed not pretty, but I think it works.

I understand the difficulty here, but it's a case of Perfect being the enemy of Good. Maybe a first step if to allow the null onBindViewHolder. For people that don't return null from the parser, this is a non-issue. And for the ones that do, they should be prepared to handle it.

Anything more at this point is not worth it, I agree.
