### ISSUE TITLE
Decrease restriction level for inner components which could be reusable

### ISSUE THREAD

**Issue by sereden** [firebase/FirebaseUI-Android#1119]
Hello everybody!

I guess library shouldn't be very strict in some aspects. For example, developers might want to implement custom phone numbers screen with validation. Currently to do this they need to implement `CountryListSpinner` class on their own with all related classes because `CountryInfo`,  `PhoneNumberUtils` and other are `@RestrictTo(RestrictTo.Scope.LIBRARY_GROUP)`

As for me some parts of the library could avoid this annotation

**Comment by samtstern** [comment]
@sereden the reason we restrict those components is because we don't want them to be considered part of the public API.  This lets us change them frequently and helps us move quickly.

If you want to use these restricted classes you can either copy the code or fork the library entirely, that's the beauty of open source!
