### ISSUE TITLE
FirebaseRecyclerAdapter only loads 1 item.

### ISSUE THREAD

**Issue by prodoxx** [firebase/FirebaseUI-Android#113]
FirebaseRecyclerAdapter keeps returning only one item when clearly there are more than one item on Firebase Reference, if that makes sense.

**Comment by puf** [comment]
In my usage the FirebaseRecyclerAdapter adapts exactly what the underlying Firebase or Query object matches. Can you provide an MCVE for your behavior that doesn't do that?

**Comment by abdyer** [comment]
@xXProdoxX I have the same issue. Are you trying to load a list populated via `.push()`? I'm fairly certain the one item you're seeing is a `HashMap<String, Model>` instead of the `List<Model>` you expect. I ran into this issue when I first looked at Firebase a couple years ago and it looks like it's still the case. As luck would have it, @puf even answered this very question [on StackOverflow](http://stackoverflow.com/questions/30744224/how-to-retrieve-a-list-object-from-the-firebase-in-android).

@puf From the `FirebaseRecyclerAdapter` source, it doesn't look like it supports this case. Is there an easier way or do we just need to roll our own adapter?

**Comment by abdyer** [comment]
A bit more information. I changed my app to only save a basic POJO with getters and now I'm correctly deserializing a collection populated via `.push()` with `FirebaseRecyclerAdapter`. The polymorphic classes I was saving before were likely causing the problem in my case.

**Comment by davidhoeck** [comment]
Same problem here? Does anybody have a solution?

**Comment by Amit0191** [comment]
http://stackoverflow.com/questions/40440624/firebaserecycleradapter-only-loads-1-item

Please help me with this. Thank you.
