### ISSUE TITLE
Is the ID token returned in a IDP Response suitable to perform an oauth login in a custom backend?

### ISSUE THREAD

**Issue by RoqueCampos** [firebase/FirebaseUI-Android#1182]
Hi!

I request apologizes, this is not an issue. I ask for clarification to know if what I'm trying to do is doable.

In the past I developed android apps which used the google-sign, and used the returned token to perform a login in a custom backend. The backend verifies that token with google again, and if all was in order, the user was identified in our backend (an account was created in the custom backend if needed).

My question is if the ID token returned in a IDP response when using the FirebaseUI-auth library to perform a login from an android app, is suitable to do the same. The idea is to send this ID token to our custom backend, and this backend will use the php library google/apiclient to perform an oauth login.

Is this possible?

Thanks and excuses if this is not the right place to ask this question.

**Comment by samtstern** [comment]
@RoqueCampos the ID token is sufficient to *authenticate* the user in your custom backend.  You can use one of the Firebase Admin SDKs to verify the token and get the user's information from it.

It is not an OAuth token though so it is not sufficient to *authorize* usage of the user's Google account.

Closing this issue since it doesn't really have to do with FirebaseUI but feel free to comment again if you have more questions.
