### ISSUE TITLE
UserInfo with provider 'firebase' showing up

### ISSUE THREAD

**Issue by samtstern** [firebase/FirebaseUI-Android#1223]
I was testing out the demo app with `3.3.0` and got this crash after signing in (with Google, but I think the account had been linked to email):

![image](https://user-images.githubusercontent.com/8466666/38051789-29f69b94-3284-11e8-82ed-0870eddb3afe.png)

This caused a crash in our provider switch statement.

**Comment by samtstern** [comment]
Looks like we knew this was possible because we skip over it in `AuthUI`:
https://github.com/firebase/FirebaseUI-Android/blob/56e4f3fe5c028993faa935a287682714ea1ac83e/auth/src/main/java/com/firebase/ui/auth/AuthUI.java#L390

**Comment by samtstern** [comment]
Fixed by #1224

**Comment by GuanacoDevs** [comment]
Not sure if this is related to [#329](https://github.com/firebase/FirebaseUI-Android/issues/329)
I wanted to get the provider to retrieve the picture profile, but the method `getProviders()` is not available.
Checking on the options there is an obscure method that returns a List, i believe is that `zza()`, but it comes with a "internal use warning and should not be used by apps"
Kept digging and ended up using `FirebaseAuth.getInstance().getCurrentUser().getProviderData().get(1);`
Am I doing something wrong?, didn't open an issue thinking that it would get fixed in 12.0.1

Best Regards

**Comment by samtstern** [comment]
@GuanacoDevs so `getProviders()` (and some other methods) were actually never meant to be exposed, but our ProGuard has been broken this whole time.

In `12.0.0` this got "fixed", sot the methods were hidden.  But of course many developers were relying on these methods.  So in `12.0.1` we opened them back up but with the lint warning you're seeing.

So you did exactly the right thing, in this case the replacement is `getProviderData()`.
