### ISSUE TITLE
version conflict 

### ISSUE THREAD

**Issue by HassanZaib** [firebase/FirebaseUI-Android#1247]
Error:FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':auth:processDebugGoogleServices'.
> Please fix the version conflict either by updating the version of the google-services plugin (information about the latest version is available at https://bintray.com/android/android-tools/com.google.gms.google-services/) or updating the version of com.google.android.gms to 11.8.0.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
BUILD FAILED in 1s

**Comment by veerendra2k1** [comment]
I am getting while compiling...

Please fix the version conflict either by updating the version of the google-services plugin (information about the latest version is available at https://bintray.com/android/android-tools/com.google.gms.google-services/) or updating the version of com.google.android.gms to 12.0.1.

**Comment by alexroode** [comment]
I ran into the same issue, even when only adding  `com.google.firebase:firebase-core:12.0.1` as a dependency, so I don't believe this is related to FirebaseUI.

I was able to resolve this issue in my project by moving `apply plugin: 'com.google.gms.google-services'`
in my app-level `build.gradle` **after** my `dependencies` section, instead before it.

This matches the order shown in the Firebase Android quickstart projects, eg.:
https://github.com/firebase/quickstart-android/blob/master/firestore/app/build.gradle

I am not sure why this makes a difference.

**Comment by samtstern** [comment]
@alexroode this makes a difference because if it's at the top of the file it will not have access to your "resolved" dependencies.  Gradle / groovy are sort of strange that way.

@HassanZaib there's not enough information here to help you out, so I will assume that @alexroode has provided the correct solution.  To recap:

  * Make sure you use version `3.2.1` of `google-services`
  * Use version `12.0.1` for all Firebase/Play SDKs
  * Use the latest version of FirebaseUI
  * `apply` the plugin at the **end** of your `build.gradle`

**Comment by zaidhayaat** [comment]
firebase-ui-firestore dependency for 11.8.0
