### ISSUE TITLE
How to require and validate user profile fields?

### ISSUE THREAD

**Issue by kiptoomm** [firebase/FirebaseUI-Android#1292]
Unlike the OP in #467, my use case actually requires the user to specify a first and last name. I understand that with email sign-in (and most of the other sign in methods), the user's displayName is enabled by default (looks like since v3.2). However, most providers (Gmail, Twitter, etc) don't require their users to have a particular name format, so parsing the displayName by splitting on space, etc doesn't seem like a robust way to gather and validate the user's names. 

Is there a way to do this with Firebase (or FirebaseUI), or must I implement my own custom views to request and validate the user input?

**Comment by samtstern** [comment]
@kiptoomm we don't have anything in FirebaseUI to make sure that the profiles from social providers are filled out.  So yes you'd have to build this yourself.

One of the features we've had on the roadmap since forever is to build in an account management UI:
https://github.com/firebase/FirebaseUI-Android/issues/235

So I think if this request ever gets done, it will be part of that effort.  Thanks for the suggestion!
