### ISSUE TITLE
What exactly is UNCHANGED_CONFIG_VALUE?

### ISSUE THREAD

**Issue by vptcr** [firebase/FirebaseUI-Android#131]
What value do i need to put in 
 private static final String UNCHANGED_CONFIG_VALUE = "CHANGE-ME";

Please help.

**Comment by samtstern** [comment]
@vptcr you don't need to change that value in the java code, but you want to change it in the [config.xml](https://github.com/firebase/FirebaseUI-Android/blob/master/app/src/main/res/values/config.xml) file if you plan to use Facebook authentication,

When your app overrides that resource value it tells the library your Facebook application ID so that it can properly initialize the Facebook SDK.

**Comment by vptcr** [comment]
But in the sample app source code there was a "Configuration required" check for Google Authentication as well as Facebook. I am only using Google Auth. 

@MainThread
    private boolean isGoogleConfigured() {
        return !UNCHANGED_CONFIG_VALUE.equals(
                getResources().getString(R.string.default_web_client_id));
    }

For only Google Auth, do I still need to add value?

**Comment by samtstern** [comment]
The web client ID value should be automatically populated once you download
the Google Services JSON file and put it in your project per the
instructions in the Firebase Console.
