### ISSUE TITLE
TransformException: Error while generating the main dex list.

### ISSUE THREAD

**Issue by emarc-m** [firebase/FirebaseUI-Android#1344]
* Android device: Pixel 2
  * Android OS version: 8.1.0
  * GMS Plugin Version: 4.0.1
  * Firebase Auth: 16.0.1
  * Firebase Core: 16.0.0
  * Firebase Database: 16.0.1
  * Firebase Invites: 16.0.0
  * Firebase Messaging: 17.0.0
  * FirebaseUI version: 4.0.1
  
Build fails when using firebase ui version 4.0.1, works on version 3.3.1

#### Observed Results:

  ```
 com.android.build.api.transform.TransformException: Error while generating the main dex list.
> Error while generating the main dex list.
  > com.android.tools.r8.errors.CompilationError: Program type already present: android.arch.core.util.Function
    > Program type already present: android.arch.core.util.Function
  ```

Please see: [SO post](https://stackoverflow.com/questions/50524672/build-fails-with-program-type-already-present-android-arch-core-util-function)

**Comment by simonlinj** [comment]
same here. my workaround was to downgrade the support library version to `27.0.2`

**Comment by samtstern** [comment]
Thank you both for flagging this.  Reading on StackOverflow this seems to be an issue with Firebase libraries / Support libraries.  It only appeared in FirebaseUI `4.0` because we updated transitive dependencies.  For that reason I will close this issue and move discussion to the SO thread.  Should be fixed with future deps/tooling updates.
