### ISSUE TITLE
How to fully customize firebaseUi Auth ?

### ISSUE THREAD

**Issue by AbuBallan** [firebase/FirebaseUI-Android#1383]
I know that we can have a LoginTheme and can inject it in the FirebaseUI Auth. Since, the library is now open sourced, is there any best way to fully customize the Login Screen?

**Comment by iamyaoxi** [comment]
What do you mean by fully customise? To what extend you want to customise Login Screen? 

FirebaseUI Auth is designed to help developers to have more focus in their main app than Login screen. That's why the UIs already pre-designed with only few customisation available. 

If you want to have your own login screen, you can always use FirebaseAuth library, and re-create your own login screen.

**Comment by samtstern** [comment]
@iamyaoxi is correct, we don't allow for "full customization" beyond changing colors, the logo, and some pieces of text.  If you need more, you'll want to build your own UI on top of the regular Firebase Auth SDK.

**Comment by samtstern** [comment]
We have a proposal to consider more customization inf #1477 if anyone would like to comment.

**Comment by husain-nahar** [comment]
I am using firebase_ui_auth for flutter. my question is how I can access to the password textfield of either sign in or signup UI inside SignInScreen.
All I want is to get the email and password entered by the user so that I can pass those credentials to my dedicated Backend server.

**Comment by thatfiredev** [comment]
@husain-nahar The correct repo for firebase_ui_auth for flutter is https://github.com/firebase/flutterfire . Please open your issue there for a better chance of getting help.
