### ISSUE TITLE
Firebase UI in Fragment for Navigation Support

### ISSUE THREAD

**Issue by MFoster** [firebase/FirebaseUI-Android#1406]
I've seen this feature request for different reasons.  However with the release of Jetpack/Android Architectural component for navigation and its dependency on fragments it would be incredibly beneficial if the Firebase UI supported fragments that could be declared as part of the navigation graph.

**Comment by samtstern** [comment]
@MFoster thanks for the feedback. I do understand how it would be useful, but it would be very hard for us to get right.  In order to create a consistent UI experience we've found it to be critical that we start everything from our own `Activity`.

I would think of FirebaseUI as if it was something completely external to your app, only accessible via `Intent` and `onActivityResult`.  I actually am not sure on what the best practice is for integrating something like that with the Navigation Support library but I'd love to hear what you think.

**Comment by MFoster** [comment]
Alright, I understand the complexity and security of user information would mandate the Firebase UI stay as its own independent activity.  I will look for solutions along the line that SUPER has recommended and get back to this thread.

**Comment by samtstern** [comment]
Thanks @MFoster.  Closing since we're not going to to take any action for now, but feel free to keep using this thread for discussion.
