### ISSUE TITLE
displayName not set when creating new email account

### ISSUE THREAD

**Issue by ambrice** [firebase/FirebaseUI-Android#1574]
I have the following function for updating firebase database user entry when a new user is created:

```
exports.addUserData = functions.auth.user().onCreate((user) => {
    console.log("Adding new user " + user.uid);
    return admin.auth().getUser(user.uid).then(userRecord => {
        var userData = admin.database().ref('/users').child(user.uid);
        userData.child('name').set(userRecord.displayName);
        userData.child('email').set(userRecord.email);
        userData.child('is_admin').set(false);
        admin.database().ref('/users_idx').child(md5(userRecord.email)).set(userData.key);
    });
});
```

When creating a new email account from the firebase-ui web library, this function triggers correctly.  When using firebase-ui android library 4.2.1, the userRecord.displayName is undefined even though a full name was entered.

**Comment by samtstern** [comment]
For FirebaseUI android this is expected behavior.  Behind the scenes we do two operations:

1. Create user with email/password
2. Immediately update the display name

It's operation #1 that triggers the cloud function, since that's when the user is created.  What I don't understand is how firebaseui-web is getting around this issue.  @bojeil-google any idea?

**Comment by ambrice** [comment]
That was originally an issue, but I worked around that in the function by calling getUser() instead of using the user that was passed into the trigger.  I don't know why that works when the user is created from the web library but not the android library.
