### ISSUE TITLE
Remove TwitterSignInHandler because its dependency TwitterKit is deprecated.

### ISSUE THREAD

**Issue by efrohnhoefer** [firebase/FirebaseUI-Android#1626]
See: https://blog.twitter.com/developer/en_us/topics/tools/2018/discontinuing-support-for-twitter-kit-sdk.html
See: https://github.com/firebase/FirebaseUI-iOS/pull/650

**Comment by lsirac** [comment]
We can't remove this and replace it with Generic IDP just yet, some changes are needed. Generic IDP was focused on providers supporting OAuth2 while Twitter uses OAuth1 for user authentication.

We're going to be making some changes to support this, and then we'll replace it with Generic IDP. 

Releases work differently for Android, which is why it'll take longer :(

**Comment by samtstern** [comment]
Version `6.2.0` has been released.
