### ISSUE TITLE
[Feature Request] Allow a default email address to be specified in AuthUI.IdpConfig.EmailBuilder()

### ISSUE THREAD

**Issue by avoirtech** [firebase/FirebaseUI-Android#1670]
It can often be the case that the calling code will have a good idea what email address the user is going to use to sign in with (for example, when resuming after sending a verification email).

It would make things smoother for the end user if we could have a method to pre-populate the email address field in the email sign in page. Something like:
`AuthUI.IdpConfig.EmailBuilder().setEmail("someone@example.com").build()`

**Comment by samtstern** [comment]
@avoirtech thanks for this!  Sounds like a nice improvement.

**Comment by danielfaust** [comment]
Is there a way to get the password the user used to sign up? Because it is needed since `FirebaseAuth.getInstance().signInWithEmailAndPassword(strEmail, strPassword)` requires it, and FirebaseUI doesn't provide this functionality.

Adding the feature of this issue would be more than just a nice improvement.

**Comment by samtstern** [comment]
@danielfaust no there is currently no way to get the password the user signed up with.  Can you file a new issue explaining what you're doing that would require this?

**Comment by samtstern** [comment]
This was released in version `7.1.0`
