### ISSUE TITLE
How to update a phone number without PhoneAuthCredential?

### ISSUE THREAD

**Issue by kiptoomm** [firebase/FirebaseUI-Android#1701]
For my app, I have to allow users to edit their phone number. I'm able to create accounts using the phone number. I know I can use the `updatePhoneNumber()` method as suggested [here](https://stackoverflow.com/a/44602133/1145905), but it requires a `PhoneAuthCredential`. I don't know how to build or obtain a `phoneAuthCredential` with FirebaseUI...

How can I go about achieving this feature using this library? I'd much rather use the library as opposed to [reinventing the wheel](https://firebase.google.com/docs/auth/android/phone-auth) since FirebaseUI already provides so many advantages. 

I have looked at https://github.com/firebase/FirebaseUI-Android/issues/864 and https://github.com/firebase/FirebaseUI-Android/issues/1235 but they don't quite address my need.

**Comment by kiptoomm** [comment]
I saw @SUPERCILEX 's [answer](https://stackoverflow.com/a/48046819/1145905) in a related question but it seems to suggest going through the auth flow again (aka "manually"), which kinda defeats the point of this library, no?

**Comment by samtstern** [comment]
@kiptoomm thanks for the feedback!  Right now we don't provide any "update" flows for FirebaseUI, we consider these out of scope at the moment since we don't have any user management features.  I do realize this would be useful, but it would add a lot of complexity to the library which we can't afford at the moment.
