### ISSUE TITLE
No Flutter examples

### ISSUE THREAD

**Issue by remoteportal** [firebase/FirebaseUI-Android#1727]
How do you configure this for Flutter?  I don't see any examples.

**Comment by samtstern** [comment]
@remoteportal we don't have direct support for Flutter in FirebaseUI at the moment, so we intentionally don't show how to configure it.  If you want to use this library in your Flutter app you will need to use [platform channels](https://flutter.dev/docs/development/platform-integration/platform-channels) in order to call out to the native Android FirebaseUI library.
