### ISSUE TITLE
Recent removal of Play Services dependency from Firebase-auth

### ISSUE THREAD

**Issue by RPCarter53** [firebase/FirebaseUI-Android#1856]
Welcome to FirebaseUI and thanks for submitting an issue!

Please take a look at [open issues](https://github.com/firebase/FirebaseUI-Android/issues?q=is%3Aopen+is%3Aissue), as well as [resolved issues](https://github.com/firebase/FirebaseUI-Android/issues?q=is%3Aissue+is%3Aclosed), to see if your issue is either already being addressed, or has been solved by someone else.

If not, please feel free to fill in the following info so we can help faster!

### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a GitHub issue.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.
  * For general Firebase discussion, use the [firebase-talk google group](https://groups.google.com/forum/#!forum/firebase-talk)
  * For help troubleshooting your application that does not fall under one of the above categories, reach out to the [personalized Firebase support channel](https://firebase.google.com/support/contact/troubleshooting/)

### Step 2: Describe your environment

  * Android device: Any but Fire tablet would be a good case in point
  * Android OS version: N/A
  * Google Play Services version: N/A
  * Firebase/Play Services SDK version: N/A
  * FirebaseUI version: 6.4.0
  
### Step 3: Describe the problem:

The latest release of Firebase-auth has removed the dependency on Google Play Service and yet FirebaseUI-auth still has this dependency. Is there any prospect of this being removed in the near future.

#### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
#### Observed Results:

  * What happened?  This could be a description, `logcat` output, etc.
  
#### Expected Results:

  * What did you expect to happen?
  
#### Relevant Code:

  ```
  // TODO(you): code here to reproduce the problem
  ```

**Comment by samtstern** [comment]
@RPCarter53 please don't file empty issues, there's no way I can know what you're asking.

If you're wondering if we can remove the Play services dependency from FirebaseUI: maybe in the long term, but not immediately.  The reason is that Google Sign In still requires Play services and untangling that dependency is going to be a pretty big project! 

But I do hope we can get there eventually.

**Comment by RPCarter53** [comment]
Thanks for the prompt response. The issue we have with Play Services is always the Amazon Fire tablets which is my some way our biggest market place. I was rather hopeful when I saw that the dependency had been removed from the underlying Firebase library. Is there any possibility of the dependency being linked just to Google Sign which I believe we could do without in the short term?

**Comment by samtstern** [comment]
@RPCarter53 yeah we'd just have to do some refactoring first!  Here's a quick glance at all the places the  `play-services-auth` library is used within our code:
https://github.com/firebase/FirebaseUI-Android/search?q=com.google.android.gms.auth

We need to isolate that usage to just a few files and then guard the usage of those files on some runtime checks for certain classes, otherwise we risk crashing a lot.

**Comment by RPCarter53** [comment]
Thanks Sam for the update. I think for now I will go with the underlying firebase-auth and just link with facebook login. I will keep an eye on firebaseUI and pick up when this dependency is gone.
