### ISSUE TITLE
Firebase AuthUI phone authentication issue solved- Firebase bug

### ISSUE THREAD

**Issue by dipanjansgithub** [firebase/FirebaseUI-Android#1859]
Pressing verify it returns back to the the AuthUI login screen. Problem was found in the Firebase Auth version 20.0.0 and BOM version 26.0.0. In the lower version it is working absolutely fine which is- implementation platform('com.google.firebase:firebase-bom:25.13.0') and implementation 'com.google.firebase:firebase-auth:19.4.0'

**Comment by JERINPWILSON** [comment]
I got this issue too. Any workarounds other than going to older version?

**Comment by samtstern** [comment]
@dipanjansgithub FirebaseUI v6 depends on `firebase-auth` version `19.x` as you can see here:
https://github.com/firebase/FirebaseUI-Android/releases/tag/6.4.0

This means it is **not** compatible with `firebase-auth` version `20.x` or `firebase-bom` version `26.x`.  This is a major version number bump and therefore a breaking change.  The main breaking change in this version of Firebase Auth was a change to Phone Auth, which is why the library crashes when you try to insert the new library and do Phone authentication.

We're already working on FirebaseUI version `7.0.0` to fix this.  You can see our progress here:
https://github.com/firebase/FirebaseUI-Android/milestone/50

**Comment by samtstern** [comment]
The fix for this issue has been released in version `7.0.0`
