### ISSUE TITLE
Make all users to have a verified phone number, even though phone number is not primary sign in method

### ISSUE THREAD

**Issue by danijorda1** [firebase/FirebaseUI-Android#1929]
I sometimes build apps (like for shipping, customer relations, maintaining people's profiles, ...), that need to have the phone number of signed-in users, and I want to use Firebase's Phone Number Authentication method to be sure that the phone number filled by signed-in users are really theirs (that is they have verified it).

Please note that I don't intend using phone number verification to be signing-in users to the apps. The users could sign in with email, or any other provider. The phone number verification could come in if the user signs-in for the first time on the app, or if they want to update their phone number. And as Firebase Authentication maintains phone number verification as a sign-in method and not as some extra feature, the best solution will be to call linkWithPhone to a newly signed-in user or to a user that lacks a phone number and to call updatePhone when the user wants to change their phone number.

**Comment by samtstern** [comment]
@danijorda1 thanks for the feedback! Since this is is a core Firebase Auth feature request and not a FirebaseUI feature request, I am going to close this issue.  The best place to report your general feature requests is here: https://firebase.google.com/support/troubleshooter/report

Just to confirm what you already know: right now Firebase Auth only supports verifying phone numbers as part of a sign-in attempt.  There is currently no Firebase API to verify phone numbers at an arbitrary point in the UI flow so developers have to use a third-party service like Twilio, etc.

**Comment by obumnwabude** [comment]
Hi @samtstern, 

I also need what @danijorda1 is requesting. 

I think it is a feature that can be added to FirebaseUI, without tampering with the core Firebase Auth. 

See it this way, that the feature is aimed at having a verified phone number, stored in every signed-in user of a Firebase project. 

Such assurance is the duty of the app implementing Firebase Auth, and not the core Firebase Auth itself. So a developer who wants to have verified phone numbers for every signed-in user, and does not want to use phone number to sign in users, will:
a. Carry out sign-in with phone number immediately after a user signs in for the first time.
b. And then, link the phone number to the signed-in user, so that users all have phone numbers stored. 
c. The app could also update phone numbers where it simply repeats a sign-in with phone number for the new phone number and then updates the phone number credential stored in the Firebase Auth User instance.

This time around, we were wondering if FirebaseUI could actually have such logic/flow, and of course, it should be optional.

@samstern please check out [this issue on FirebaseUI-Web](https://github.com/firebase/firebaseui-web/issues/774) for a suggested implementation.

**Comment by samtstern** [comment]
@obumnwabude understood! That is a reasonable idea and something that can be done at the UI layer if you want. However we don't plan to add any more optional flows to FirebaseUI at this time.

**Comment by obumnwabude** [comment]
@samtstern thanks for appreciating the idea.

Okay, given that FirebaseUI doesn't plan to add UI flows now, is there anytime you would like to do so ?

**Comment by samtstern** [comment]
@obumnwabude no I don't see us adding this flow to FirebaseUI in the future.
