### ISSUE TITLE
Firebase phone auth OTP no longer being read automatically

### ISSUE THREAD

**Issue by vijtheveg** [firebase/FirebaseUI-Android#1948]
* Android device: Any device
  * Android OS version: Any version
  * Google Play Services version: com.google.gms:google-services:4.3.8
  * Firebase/Play Services SDK version: com.google.firebase:firebase-auth:21.0.1
  * FirebaseUI version: com.firebaseui:firebase-ui-auth:7.1.1
  
#### Steps to reproduce:

OTP was being read automatically in my app for many months now. It has suddenly stopped working in the last few weeks. There are no specific steps to reproduce - OTP is never read automatically anymore.

I have verified that the SMS template being used is correct and matches the OTP received. I have also enabled Android SafetyNet  / app verification, to no avail.

**Comment by Glaubenio** [comment]
I'm having the same issue, any clue on how to solve this?

**Comment by samtstern** [comment]
@vijtheveg without specific steps to reproduce, this is impossible to debug. It sounds like if there *is* a bug it would be in the Firebase Android SDK not FirebaseUI since the base SDK is responsible for reading the OTPs.

If you can gather enough information to make this debuggable, please file an issue on the firebase-android-sdk repo.

**Comment by vijtheveg** [comment]
Hi Sam,

Instead of closing this issue, can you please let me know what further information you need to debug the issue? I can then try to provide logs, code snippets, etc.

Please do let me know. 

Thanks!

**Comment by samtstern** [comment]
The issue template has the information required:
https://github.com/firebase/FirebaseUI-Android/issues/new
