### ISSUE TITLE
Retrieve User email from Google and Facebook Providers

### ISSUE THREAD

**Issue by davidgcalle** [firebase/FirebaseUI-Android#199]
I need to allow multiple accounts and if one has Email and password auth, and later wants to sign in with facebook or google,  I need to retrieve the user Email and assing the result info to my user data.

As mentioned on here https://github.com/firebase/FirebaseUI-Android/issues/181, says that I can retrieve it from AccesToken and GoogleSignInAccount, but don´t see how,  could please clarify that. 
Thanks

**Comment by samtstern** [comment]
@davidgcalle I am just seeing this issue now, sorry about the very long delay.  Could you please explain this request in a little more detail?  I'm not quite sure what you are trying to achieve.

**Comment by SUPERCILEX** [comment]
If the user signs up with email@example.com and has a Facebook or Google account with that same email address, the user id will be the same and you can just retrieve the email with `FirebaseAuth.getInstance().getCurrentUser().getEmail();`.

If you are referring to the user having two different emails addresses count as one, that's not possible at the moment. For example, a user cannot sign up with email@example.com and then later on do so using Facebook or Google with another.email@example.com. To my knowledge, this would be considered two different user accounts with two different user ids.

I'm actually working on a feature that lets you link accounts together: I have it set up so that you can add a `linkWithCurrentUser()` option to the `SignInIntentBuilder()` to easily link accounts together (including anonymous authentication). If this is what you are looking for, either I'll get it done sometime soon in my spare time, or someone else will get around to it before 1.0.0 (hopefully).
