### ISSUE TITLE
Firebase-UI and Espresso testing

### ISSUE THREAD

**Issue by peterhav** [firebase/FirebaseUI-Android#200]
Hello, I'm using this library for quite some time now and it works fine. Thanks for the effort!
At this moment I'm running into an issue setting up my test code: I would like to sign in a (test) user using an Espresso test case. Starting the sign in flow works fine, but as soon as I need to click the "NONE OF THE ABOVE" button in the email selection dialog, I run into the issue that this code is not part of the library (I'm not able to click on it within the test cases). 2 possible options that might help:
1. make the email selection behavior part of the library (in order to make Espresso testing possible)
2. make the behavior optional (e.g. with a disableMailSelectionDialog method on the createSignInIntentBuilder)?

Not sure if this is technically possible and maybe there are better more elegant solutions?

**Comment by samtstern** [comment]
@peterhav thanks for the report.  You're right, there is more we could do to enable Espresso testing.

I believe the dialog you're talking about is the email selection dialog from Google Sign In.  As you said, it's not in the application code because that's actually a system dialog served by Google Play Services.  In the past I have personally used UiAutomator tests to test that flow but I'll see if I can think of a way to enable Espresso testing there.

**Comment by SUPERCILEX** [comment]
@peterhav I'm not sure if this is still relevant, but the new FirebaseUI versions have a `setIsSmartLockEnabled(boolean)` which would let you disable the Google Account Picker dialog. Then you can sign in via email using a fake account for your Espresso tests.

@samtstern I'm combing through old issues here, would you consider this one resolved?

**Comment by samtstern** [comment]
I guess this is as resolved as it is going to be.  SmartLock and Google Sign In both display their UI from Google Play services so there's no way to use Espresso testing for them.  I tend to avoid them in tests when possible and use UiAutomator tests (slow, but can access anything on the screen) when I can't.
