### ISSUE TITLE
Add proper dialog in case Google Play Services has wrong version

### ISSUE THREAD

**Issue by peterhav** [firebase/FirebaseUI-Android#220]
FirebaseUI version: 0.4.3

### Step 3: Describe the problem:

When Google Play Services does not have the proper version number a progress monitor will keep showing forever when starting the SignInIntent. In the console the following type of messages are shown:
 
#### Observed Results:

D/FirebaseApp: Notifying background state change listeners.
D/FA: Application backgrounded. Logging engagement
D/FA: Logging event (FE): _e, Bundle[{_o=auto, _et=26619}]
V/FA: Using measurement service
V/FA: Connecting to remote service
W/GooglePlayServicesUtil: Google Play services out of date.  Requires 9256000 but found 8489070
W/FA: Service connection failed: ConnectionResult{statusCode=SERVICE_VERSION_UPDATE_REQUIRED, resolution=null, message=null}
  
#### Expected Results:

I would expect the library to show the user a message indicating that their Google Play Service version requires to be updated (if possible by showing a button to perform the update).

**Comment by samtstern** [comment]
@peterhav thanks for the feedback.  I agree this is something that the library should handle since it claims to do all the UI work.

The good news is you can do this yourself in only a few lines of code.  In the [GoogleApiAvailability](https://developers.google.com/android/reference/com/google/android/gms/common/GoogleApiAvailability) class the methods `isGooglePlayServicesAvailable` and `getErrorDialog` will do most of the work for you.

**Comment by samtstern** [comment]
@peterhav this is now implemented, fix will be rolled into the next release

**Comment by peterhav** [comment]
Great, looking forward to the next release!

**Comment by samtstern** [comment]
0.4.4 has been released!
