### ISSUE TITLE
.setTosUrl() in chrome custom tabs

### ISSUE THREAD

**Issue by krisu7** [firebase/FirebaseUI-Android#225]
Hi, can you add possibility to open .setTosUrl() link in Chrome Custom Tabs?
I want to customize user experience and I kind of cheat now using css.
If it's possible now, how can I achieve it?
Thanks in advance

**Comment by samtstern** [comment]
@krisu7 this library is intended to work across a wide spectrum of Android devices, many of which do not have Chrome installed.  I think the best solution would be to minimize your use of Chrome-only CSS so that your ToS renders properly in any browser (WebView, Samsung Browser, Baidu browser, etc).
