### ISSUE TITLE
Creating a Firebase SpinnerAdapter

### ISSUE THREAD

**Issue by TheCraftKid** [firebase/FirebaseUI-Android#304]
During a project I've been working on, I have created a SpinnerAdapter modeled after the FirebaseListAdapter, and I was going to submit a pull request until I saw something about submitting an issue request about any changes wanting to be made. Simply put, can I submit a PR containing a SpinnerAdapter that recieves data from a DatabaseReference or Query? I've seen another PR that messed with FirebaseArray, but it doesn't seem like it conflicts.

Thanks.

**Comment by puf** [comment]
What does this adapter change about the existing behavior?
Will you also be submitting a corresponding PR for FirebaseUI-iOS?

**Comment by TheCraftKid** [comment]
It adds the functionality to specify a dropdown view along with the standard view it shows when not selected. I will if submit a PR for this in FirebaseUI-iOS if this isn't too redundant.

**Comment by puf** [comment]
Sorry, I'm still not very clear on what this does. The goal of submitting
an issue before a PR is so that we can discuss the feature and its merits
first.

What is the goal of the dropdown view? Is it being populated from a
FirebaseArray?

Given that you have this working in an existing project: a screenshot might
clarify this more quickly.

**Comment by TheCraftKid** [comment]
Sorry for the wait.

I'm essentially proposing this

![](https://dl2.pushbulletusercontent.com/PqCfcaHg2r4YH3UR2gLjtiMlTAP0R95V/Screenshot_20160913-192517.png)

and this

![](https://dl2.pushbulletusercontent.com/G3qYgqsJ54f89cpwzQnQHJjjoiNkrJVx/Screenshot_20160913-192508.png)

populated by this:
![firebase console](https://cloud.githubusercontent.com/assets/16641570/18497427/bfb87364-79f3-11e6-89e9-5a47eafd011f.jpg)

**Comment by TheCraftKid** [comment]
Does this feature seem worthy enough to implement?

**Comment by puf** [comment]
Hey @TheCraftKid . The screenshots and data structure indeed help. It looks like it could work. So far we've intentionally kept the number of components/adapters in the library low, so that we can focus on getting the core functionality right. I'd like to stay that course for a bit longer.

But your component sounds like a great separate library, that could then internally use FirebaseUI. That would also solve the problem that FirebaseUI requires that we offer the functionality on both iOS and Android, which is holding a lot of other PRs back.

Can you try putting the component(s) into a separate library that uses FirebaseUI? It would be a good test-case for our extensibility model.

**Comment by TheCraftKid** [comment]
Sorry for prematurely submitting the PR. I'll take that suggestion, though. Thank you!

**Comment by puf** [comment]
No problem. I read the issue first and only then saw that your PR was
already doing what I proposed. Looks like a nice, simple, clean UI
component, so is great proof that you can build upon FirebaseUI. A separate
repo would be a great place to keep other custom components.
