### ISSUE TITLE
Double password visibility toggles

### ISSUE THREAD

**Issue by nicbell** [firebase/FirebaseUI-Android#347]
When using `com.firebaseui:firebase-ui-auth:0.6.0` with Android Support Library, revision `24.2.0`. I get two icons to toggle password visibility because this feature is now built-in.

As temporary fix I have downgraded my Android Support Library to `24.1.0`.

**Comment by samtstern** [comment]
@nicbell thanks for the report!  We're actually using `23.x` for all our testing for other reasons, so we hadn't seen this yet.

**Comment by SUPERCILEX** [comment]
I noticed this issue before, but never bothered to do extensive research on it because I thought it was an isolated issue. I did however notice that if you don't set the eye drawable it still shows up which is weird. Since somebody else noticed this issue on the same version of the support lib that I'm using, I decided to check the release notes and indeed in v24.2.0 they added the password visibly toggle as the default. I'll submit a PR upgrading us to 24.2.1 unless somebody else wants to.

**Comment by samtstern** [comment]
@SUPERCILEX the reason we're not on `24.x` is because Robolectric still only has support for API <= 23, so if we go to 24 we lose testing (or we're testing strange zombie code, which is just as bad).

**Comment by SUPERCILEX** [comment]
Mockito 2.x came out. Doesn't it support api 24?

**Comment by samtstern** [comment]
It's Robolectric, not Mockito.

We can try specifying `sdk = 23` in the `@Config` annotation in all of our tests and then upgrading to support `24.x.x` and SDK `24`, if that works I'd be OK with it.

**Comment by SUPERCILEX** [comment]
My bad, I'll try getting Robolectric to play nice tonight.

**Comment by samtstern** [comment]
Thanks to #349 by @SUPERCILEX I was able to push version `0.6.1` which has all the latest dependencies and should no longer have this issue!
