### ISSUE TITLE
Disable account creation

### ISSUE THREAD

**Issue by JacobVanAssche** [firebase/FirebaseUI-Android#385]
Is it possible to only allow for users to login if they have an account and disable account creation? I want to be able to manually add accounts and allow users to login. I do not want them to be able to create accounts.

**Comment by samtstern** [comment]
@JacobVanAssche I can see the use case here but I don't think this is something we will support in FirebaseUI, since the goal of the library is to implement *all* the auth flows in a simple way with as little configuration as possible.  The more "disable foo" or "enable bar" settings we add, the more complexity we get and the more chances we have for error.

Thanks for the suggestion!

**Comment by samtstern** [comment]
See #530
