### ISSUE TITLE
Is it possible to override the default layout of the auth login activity with another xml?

### ISSUE THREAD

**Issue by juanlet** [firebase/FirebaseUI-Android#427]
I find that I need to add some logo and colors and do customization to the layout positioning elements in certain part of the layout, is it possible in the newest version to do that?....Cause a couple of months back it wasn't possible. Thank you!

**Comment by wilik16** [comment]
Yes, it's possible. I have been overriding the layouts in my app even before the newest version.
What you need to do is just find the layout that you want to override at [https://github.com/firebase/FirebaseUI-Android/tree/master/auth/src/main/res/layout](here) and then create or copy the file (don't change the file name) to your app's res/layout folder. In the new file, you can freely change the position of the views or even add new views, just make sure the `id` of the current views remains unchanged.

**Comment by samtstern** [comment]
@juanlet the advice by @wilik16 is correct because if Android sees two resources with the same ID it will choose the one higher in the dependency tree, in this case your app module is always higher than the firebaseui library.

I'd warn you to be careful when upgrading FirebaseUI versions when using this approach.  If we change any resource IDs you could see strange UI bugs or even crashes, and because we don't consider resource IDs to be part of the "public API" we don't list such changes in the release notes or put much effort into tracking them at all.
