### ISSUE TITLE
Is 1.0.1 is compatible with 10.0.1?

### ISSUE THREAD

**Issue by kirtan403** [firebase/FirebaseUI-Android#430]
I have seen firebase has release 10.0.1 version of the firebase sdks. So I just wanted to ask is 1.0.1 is compatible with firebase sdks 10.0.1?

**Comment by SUPERCILEX** [comment]
Sadly, no. You can find a compatibility table [here](https://github.com/firebase/FirebaseUI-Android#compatibility-with-firebase--google-play-services-libraries).

However, there is a [trick](https://github.com/firebase/FirebaseUI-Android/issues/414#issuecomment-262283040) to use the latest version of play services. Hope that helps!

**Comment by samtstern** [comment]
Actually in this case they will be compatible, because the only difference between `10.0.1` and `10.0.0` is a change in the `AndroidManifest` to remove some permissions that were included by a mistake in the build system.

The incompatibilities come from mixing versions that were not compiled/proguarded together, but I believe that these two versions should work together.

However take all of that with a grain of salt, there's really no way for me to guarantee this so it's worth testing for yourself.

**Comment by SUPERCILEX** [comment]
Oh, I get it now! The reason, we get a compile error saying it couldn't find method zzza or something is because `com.google.android.gms` will have been obfuscated differently than another version of itself. Same goes for `com.google.firebase`. Very cool! Thanks for the explanation @samtstern!

**Comment by kirtan403** [comment]
@samtstern Thanks for the explanation. I will better wait for the next update! 👍 

@SUPERCILEX Nice trick! Will use when needed. Thanks 😄
