### ISSUE TITLE
Add entries to Sign Up

### ISSUE THREAD

**Issue by dpbalcena** [firebase/FirebaseUI-Android#437]
Is it possible to add entries to Sign up e.g. Username, Age etc.

**Comment by SUPERCILEX** [comment]
FirebaseUI doesn't support this because Firebase the platform doesn't support it. [Firebase supports](https://firebase.google.com/docs/reference/android/com/google/firebase/auth/FirebaseUser) adding a name and a profile pic and that's about it. They do this because Firebase will never be able to know what every single developer wants a profile to look like.

To get around this, I think the easiest solution would be to use the realtime database. If the sign in is successful in `onActivityResult`, you could launch some sort of "Tell us more about you" activity or fragment. Once the user gives you all the information you need, you can use  [`FirebaseUser#getUid()`](https://firebase.google.com/docs/reference/android/com/google/firebase/auth/FirebaseUser.html#getUid()) and store the profile info in the realtime database. You can also store the name and profile pic uri to make a complete `User` object to retrieve from the database.

To make collecting this information this easier, FirebaseUI could possibly expose some sort of api that would let devs request a list of fields to be filled out in the RegisterEmailActivity and return them in `IdpResponse`, but that would be a discussion to have with @samtstern.

Hope this helps!

**Comment by samtstern** [comment]
@dpbalcena thanks for the feature request.  I believe this is the same as #235.  We are actively considering adding this as our next major feature but we're trying to figure out how to make it customizable while maintaining simplicity.

For now the best route, as @SUPERCILEX  said, is to use the Firebase Database for this and build your own user management UI.  If you have more thoughts about this, please chime in on #235.
