### ISSUE TITLE
io.fabric.ApiKey at [com.firebaseui:firebase-ui-auth:1.0.1] AndroidManifest.xml is conflict with the app's

### ISSUE THREAD

**Issue by bobshao** [firebase/FirebaseUI-Android#450]
Hi Team,

Now there is a io.fabric.ApiKey at [com.firebaseui:firebase-ui-auth:1.0.1] AndroidManifest.xml.
But I have another io.fabric.ApiKey in my app's AndroidManifest.xml. Mine is for fabric Crashlytics.
what should I do for this? Thanks.

**Comment by samtstern** [comment]
I believe there are two ways to get around this:

1. We use `@string/twitter_consumer_secret` to store the Fabric API key. If you define a `<string>` resource in your app with the same name, you will override ours.
2.  Add `tools:node="replace"` to your `meta-data` element, which will tell Android to use yours over any lower-priority conflicts.

**Comment by bobshao** [comment]
Hi @samtstern , thanks for your response. Yes, you are right, I can use my Fabric API key by following your ways. But if I do this, I think fabric Crashlytics will work well, but I am not sure whether firebase-ui twitter auth part will work well?

**Comment by SUPERCILEX** [comment]
Hey @bobshao, you'll want to use the second method:
```xml
<meta-data
    android:name="io.fabric.ApiKey"
    android:value="key"
    tools:replace="android:value"/>
```
The consumer key and ApiKey are different, but it doesn't really matter because we aren't using it anyway; we put the metadata in there to fix a memory leak twitter caused without it.

PS: I tested it with the `ApiKey` generated [here](https://fabric.io/kits/android/twitterkit/install) and the consumer/secret from my Twitter app dashboard.

**Comment by bobshao** [comment]
Hi @SUPERCILEX , thanks very much for your verification, I have no question now.
