### ISSUE TITLE
the have problem i need help tried whole day . . 

### ISSUE THREAD

**Issue by champrocks3190** [firebase/FirebaseUI-Android#513]
i used 

 mstore=FirebaseStorage.getInstance().getReference();

        StorageReference st= mstore.child(Constants.FIREBASE_USERS_IMAGE);

            Glide.with(context)
                    .using(new FirebaseImageLoader())
                    .load(st)
                    .signature(new StringSignature(System.currentTimemIllis()))
                    .into(fragcm);

now there are two opions for me 
1 ) to load image each time using signature of current time to update it , 
2) and other if i dont use it load old cache image , 
need : - 
i want the proper update of image and load cache only as its updated and loaded once

**Comment by samtstern** [comment]
This is the same is as #479 so let's discuss there.

Right now we don't have a good solution to this because there is no metadata available at the time of starting the load.  What you're doing with `StringSignature` will work except you'll have no caching.

Some possible workarounds include:
   * Don't change images at the same Storage location, instead upload a new image and replace the reference you're holding.
   * Create some "bucketed" version of your timestamp signature pattern to make sure the cache is updated with a certain frequency (like every day or month).

**Comment by champrocks3190** [comment]
hey sam i solved thanks ,

**Comment by champrocks3190** [comment]
i solved different way what i do is get path from the onresult activty and use as string signature and that same signature pass to constant or as shared prrefrence to other activities where want to show same image , it will load once and use cache untill dont update the profile pic
