### ISSUE TITLE
Sorting and filtering doesn't work with indexed data

### ISSUE THREAD

**Issue by rmunk** [firebase/FirebaseUI-Android#537]
* Android device: Samsung Galaxy J5
  * Android OS version: 5.1.1
  * Google Play Services version: 10.0.84
  * Firebase/Play Services SDK version: 10.0.1
  * FirebaseUI version: 1.1.1

I use indexed data in the real time database with `FirebaseIndexRecyclerAdapter` and are unable to get sorted or filtered data from the database. Lets assume data that is structured like this:
```
{
  "providers": {
    "provider_1": {
      "name": "Provider A",
      "rating": 2.5,
      "sale": false
    },
    "provider_2": {
      "name": "Provider B",
      "rating": 4.0,
      "sale": false
    },
    "provider_3": {
      "name": "Provider C",
      "rating": 3.5,
      "sale": true
    },
    . . .
  },
  "categories": {
    "category_1": {
      "provider_3": true,
      "provider_2": true
    },
    "category_2": {
      "provider_3": true,
      "provider_1": true
    },
    . . .
  }
}
``` 
If I wanted to get providers from Category 1 ordered by name or rating I would expect to make an adapter with following parameters:
```
Query keyRef = FirebaseDatabase.getInstance().getReference()
        .child("categories")
        .child("category_1");

Query dataRef = FirebaseDatabase.getInstance().getReference()
        .child("providers")
        .orderByChild("name");
        // .orderByChild("rating"); // ALTERNATIVELY ORDER BY RATING

adapter = new FirebaseIndexRecyclerAdapter<Provider, ProviderViewHolder>(Provider.class,
        R.layout.item_provider,
        ProviderViewHolder.class,
        keyRef,
        dataRef) {
    @Override
    protected void populateViewHolder(ProviderViewHolder viewHolder, Provider model, int position) {
        // Data binding stuff...
    }
};
```
But the data always comes in order it is declared in the `category_1` node.

Also, if I wanted to filter providers that have items on sale I would expect to make `dataRef` query like this:
```
Query dataRef = FirebaseDatabase.getInstance().getReference()
        .child("providers")
        .orderByChild("sale")
        .equalTo(true);
```
But again, data that I get is not filtered and I get both providers instead of getting only `provider_3`.

Is there maybe something I missed when structuring my data or the way such case should be handled?

**Comment by SUPERCILEX** [comment]
@rmunk Filtering is done on the key side of things so use `ref.child("categories").child("category_1").orderByValue()`. This is an intentionally decision for several reasons:
1. It makes reading the console easier: if you have 1 million entries in `provider_1` from all you different users, finding the order of those values is impossible because they're going to be all mixed up from different users. Finding the order from the 10-50 values in your key ref is much easier.
1. Ordering by data ref is a mess because you'll have a bunch of identical priorities from all your different users dumping data in there whereas you only have a single set of priorities in your key ref.
1. And most important of all, **ordering by key allows for flexibility**. Here's what I mean:
```json
{
  "data": {
    // This order doesn't matter, the order is taken from keys/(user1 or user2).
    "3": true,
    "1": "some data",
    "2": 5
  },
  "keys": {
    // These two users can have different orders for their data,
    // something that isn't possible if you order data in the data ref instead of the key ref.
    "user1": {
      "1": true,
      "2": true,
      "3": true
    },
    "user2": {
      "3": true,
      "2": true,
      "1": true
    }
  }
}
```

Because this has been a point of confusion in the past, I've created #541 to clear things up.

**Comment by rmunk** [comment]
@SUPERCILEX I am not sure this solution applies to my case. What if have my indexed data stored as objects and I want to give the use possibility to sort and filter data on different child values. 

E.g. usually I want to see all the restaurants from the _Mexican_ category ordered by rating but when I am looking for the one I think I know it's name I want to sort them by name. Or I want to see only restaurants in the Mexican category that serve tacos. I can't get all these different filter combinations just by ordering keys in _Mexican_ category. Should I maybe structure the data differently?

I would also be satisfied doing this with client-side filtering and sorting but it is not available at the moment. Do you maybe plan to add it also to the `FirebaseIndexRecyclerAdapter` (#15)?

**Comment by SUPERCILEX** [comment]
@rmunk How many different ways do you want to order your data? Firebase [encourages duplicating data](https://firebase.google.com/docs/database/android/structure-data#fanout) so yeah, you should probably change your data structure to duplicate the data from your `dataRef` that you want to use to sort stuff in your `keyRef`. Here's how I do it in my app:
```javascript
{
  "team-indices": {
    "uid": {
      // If you need other ways to sort your data, just duplicate it here.
      "key1": 955,
      "key2": 2521,
      "key3": 4488
    }
  },
  "teams": {
    "key1": {
      "name": "CV Robotics",
      "number": 955,
      "timestamp": 1485068517786
      // Other stuff
    },
    "key2": {
      "name": "SERT",
      "number": 2521,
      "timestamp": 1485068517926
      // Other stuff
    },
    "key3": {
      "name": "Shockwave",
      "number": 4488,
      "timestamp": 1485135030569
      // Other stuff
    }
  }
}
```

Then your `keyRef` can be `root.child("team-indices").child("uid").orderByValue()`. Would this work for you?

**Comment by rmunk** [comment]
@SUPERCILEX It could work I guess in simpler cases but than you need to update the changes to sort-by values in all the places where they are used for sorting. 

E.g. when rating of restaurant changes you also need to update it in all the categories that have that restaurant. Even worst case is if you want to also have a list of favorite restaurants for each user. Then you would also need to update the rating value for the each user with that restaurant in his favorites list. 

And it seems to me it kind of beats the purpose of indexing which is to have all the data in one place and just reference it by key in other places so you don't have to update the changes in multiple places. Especially since you don't always know all the places where this data is referenced. E.g. when you update the restaurant rating or name or whatever value is used for filtering you don't know exactly which users have it in their favorites list. So on every restaurant value update you need to iterate through all the users just to update their corresponding indexed values.

**Comment by SUPERCILEX** [comment]
@rmunk Hmmm, yeah I see how that doesn't really work. In FirebaseUI `v1.2.0` you'll be able to intercept `onChildChanged` events so I guess you could do your own sorting and filtering. Other than that, I can't offer much help.

Even if we did decide to do `dataRef` ordering, I don't see any reasonable way to do it on our side without being told how to order it (which would be device side ordering/filtering; something FirebaseUI doesn't want to do). How it works: we get notified every time a new `keyQuery` child gets added and we start listening for the `dataRef` child at the key from the child `keyQuery` gave us. We have no knowledge of anything order wise in `dataRef` because we are just picking out a single child using a `ValueEventListener`.

Adding support for indexed data was one of my first PRs and at that point I was excited because I had just understood how inheritance worked with `DatabaseReference` extending `Query` and such. Anyway, the point is I made a huge mistake by letting people pass in a `Query` for `dataRef` instead of forcing them to use `DatabaseReference` which would have more accurately represented the api's abilities.
(Just FYI, `Team.getIndicesRef().orderByValue().getRef()` does not actually order by value which is counter intuitive because `DatabaseReference` _is_ a `Query`. The `getRef()` method strips all ordering and filtering info from the ref.)

@rmunk If you can find some magical solution, I would love to hear it, but for now I think you'll be stuck doing on device sorting. Sorry!

PS: if #544 goes through, this issue will be "fixed" as in you won't be able to pass in a `Query` for `dataRef`.

**Comment by rmunk** [comment]
@SUPERCILEX Thanks for the effort. I guess I will have to wait for `v1.2.0`. Do you have any idea how far away is it?
I considered forking off and trying to implement it myself but then I realized you are just individually picking children from the key list so I stopped there. I guess there is no magical solution I can think of right now...

**Comment by SUPERCILEX** [comment]
@rmunk See https://github.com/firebase/FirebaseUI-Android/issues/549#issuecomment-275716051. Yeah, sorry it didn't work out, I don't think there's a way to do it without on device sorting.

**Comment by cutiko** [comment]
Can you please improve documentation to use this properly, I have read "A note on ordering" but can't really understand it. An example would be clarifying, was looking for it in the demo app, but couldn't find it. Also did some search on SO but keep bouncing back to this issue. I'm only asking for this improvement because I have being trying to deal with this since last week. I have got some index adapter working previously, but I'm getting convinced, it's working but not implemented correctly. What the most confuse me is there are 2 lists/nodes (the dataRef and keyRef), giving a paragraph or two to explain the relation between it would be great. Thanks.

**Comment by SUPERCILEX** [comment]
@cutiko Are you familiar with how [ordering works with Firebase in general](https://firebase.google.com/docs/database/android/lists-of-data#sorting_and_filtering_data)? My little `Note on Ordering` section was just intended to explain `FirebaseIndexArray`'s ordering implementation, not a general intro to ordering in Firebase.

**Comment by cutiko** [comment]
@SUPERCILEX I'm sorry for taking so long to answer but as you point I was not familiar with ordering. I have made a simple indexed adapter working, so now I feel with a better ground to point a constructive suggestion. Before this, I have to acknowledge that you have a point, this documentation should not be an introduction to Firebase, so my suggestions will be based on improving documentation for the purpose of the section itself.

1. Something that got my on track was this [great video about a "look-up"](https://youtu.be/i1n9Kw3AORw?t=2m22s) maybe you could add it as a reference as you have added the documentation

2. Something that got me really confused was the values in the "data" node shown inside the JSON structure. Since every value is a different object -something unusual at least for Android dev- it was harder to understand it. If you could please look at this [JSON file](https://www.dropbox.com/s/8g7zaj1xf7lehd8/indexed.json?dl=0) maybe something like that will be easier to read to other devs as well

I hope to be constructive with my suggestions, thanks to all for the great work!

**Comment by samtstern** [comment]
I am going to close this issue as improving the indexed adapters is no longer a goal of the library.  Instead we hope to improve the interfaces so that developers can make these improvements in their own subclasses/forks.

I believe the improvements we've done so far (in `1.2.x` and `2.0.x`) go a long way towards this.

Thanks for the great discussion!

**Comment by Chaachii2797** [comment]
good morning! can someone please help me, i am struggling on how to sort data based on ratings saved in firebase node.. can someone please help me on how to do it?

Thanks in advanced

**Comment by mcfriske** [comment]
@Chaachii2797 Are you using Firebase - Cloud Firestore? If so, I believe what you want is to create an index that states how something should be ordered. I did it for mine for an ordering hierarchy.. But I am not 100% certain. Still new with Firebase.

**Comment by apexkid** [comment]
+1 to this issue. I will love to see a feature where it is possible to sort using dataRef's child values. This is a very basic and widely used case and should definitely be part of firebase-ui to encourage its mass adoption. I have been using this for quite sometime and I see too many obvious features missing from this library second of which is pagination. Having said so i believe this library does simplify many things so it will be great if some common developer usecases are supported as part of it so that people don't end up writing their own version of firebase ui from scratch. 

My data is having a similar structure like reported in the issue:
```
userchatgroups:
     userId1:
           grp1
           grp2

chatgroups:
    grp1:
        participants: ...
        lastMessageSentTime: <epoch time>
```

Now when i write an indexed query on `userchatgroups/userId1` but i do not want to order data based on when a chat group was created (which will be represented by order of keys). I want to order data based on the child element `lastMessageSentTime`.
