### ISSUE TITLE
OAuth Token for Google APIs from Firebase Auth

### ISSUE THREAD

**Issue by shiami** [firebase/FirebaseUI-Android#615]
After I logged in using Firebase Auth with Google account, 
can I use the identity to call other Google services (for exmaple, Youtube Data API) directly?﻿

I have done the steps described in the link:
https://firebase.google.com/docs/auth/android/google-signin

How can I get the OAuth token? Is there a way to use Google API directly?

**Comment by samtstern** [comment]
@shiami you can get the OAuth token using `GoogleAuthUtil` however this approach is deprecated.

The preferred approach is to use the `GoogleAccountCredential` API to interact with the Java client library for the API you want to contact.  I have an example here that shows how to do it for the People API, which I believe works the same (with respect to auth) as the YouTube Data API:
https://github.com/googlesamples/google-services/commit/b0113d5de80a3368fbcc347a8d522aa9ec36003f#diff-e85694daf9f925d71c478b2cde015198R273

If you have any more issues with this technique, please raise them on the google-services repo.  Thanks!

**Comment by j-melling** [comment]
@samtstern how does your example use Firebase though?
Should we follow https://firebase.google.com/docs/auth/android/google-signin to integrate the google sign in back to Firebase along with your extra code for the API setup/calls?

Could a user use a different initial Google account for a Firebase login and then a different Google account for the API calls?

**Comment by samtstern** [comment]
That example does not use Firebase, because it's not really related here.  You want to do a few things:

  1. Authenticate the user with Google, this confirms who they are.
  2. Further ask for **authorization** to access Google APIs on their behalf.
  3. Pass the Google identity for Firebase to get authenticated with Firebase as the Google user.

The steps to do "2" can be seen in the example above, the steps to do "3" are handled by FirebaseUI or can be done manually using the docs you linked.
