### ISSUE TITLE
How can i use custom ui for Firebase auth ui

### ISSUE THREAD

**Issue by MalindaWMD** [firebase/FirebaseUI-Android#619]
Hoe can i use a completely new ui for FIrebase auth ui. I customized theme using your guide, but now i need to use a new UI Like this ![image](http://www.androidhive.info/wp-content/uploads/2012/01/android-login-and-registration-screen-design.jpg).

**Comment by yudhir** [comment]
I want to Change Up Background and Put some logo.

**Comment by samtstern** [comment]
@MalindaWMD @yudhir right now you have the following options:

- We support a custom logo, it's part of the intent builder
- You can definitely add custom colors by modifying the theme and passing it to the intent builder

Putting an image in the background or moving the UI elements around right now involves some unsupported hacks, sorry!  You can look around in the other issues to see what people have come up with.

Closing this issue since the information is duplicated elsewhere.

**Comment by MalindaWMD** [comment]
OK. thank you

**Comment by samtstern** [comment]
We have a proposal to consider more customization inf #1477 if anyone would like to comment.
