### ISSUE TITLE
Filtering of Datasnapshot

### ISSUE THREAD

**Issue by Silex93** [firebase/FirebaseUI-Android#646]
Hello Good Day,

I have been trying many ways to do some client-side filtering on the data snapshot obtained. I am using the FirebaseRecyclerAdapter. I have data looking like:

{
  "19880126008-15a0be351d5" : {
    "address" : "36 Green Lane, Moon plaza",
    "dispEmail" : "bobby22@gmail.com",
    "firstName" : "Derrick",
    "lastName" : "Walker",
    "state" : "Package Ready"
  },
  "212903812903-2121212313" : {
    "address" : "59 Picadilly Street, Sunny city",
    "dispEmail" : "royh33@gmail.com",
    "firstName" : "Roy",
    "lastName" : "Harper",
    "state" : "Package Ready"
  },
 "212903812903-21212131413" : {
    "address" : "59 sun road, Sunny city",
    "dispEmail" : "royh33@gmail.com",
    "firstName" : "Susan",
    "lastName" : "Harper",
    "state" : "Package Ready"
  }
....
}

And I want to only want to  populate the Recycler view with only records that match a certain email AND has a state of package ready. Curently I am already using a sort and filter Query as provided by firebase to show only records in the state "Package Ready"but i also need to display only records with a certain email eg. royh33@gmail.com...

I have tried overiding the parsesnapshot but that wont help as even if I return a null object and check it in populate view holder, it would be too late as the view is already created. Im thinking i have to override the oncreateViewholder but not sure how or what to do since i have no access to the snapshot there...

**Comment by samtstern** [comment]
@Silex93 I can give a few quick suggestions but I am going to close this issue since it should be moved to StackOverflow.  Issues filed in this repository should be about bugs in the library code itself.

You can do a few different things:

  * In `populateViewHolder` you can hide any view that does not match your filter
  * You could restructure your data so that packages are accessed at (or copied to) `/packages/{user email}/{package id}` and then this would only be a single filter
