### ISSUE TITLE
Facebook Login Unsuccessful debug_token response from Facebook

### ISSUE THREAD

**Issue by DiegoBaldi** [firebase/FirebaseUI-Android#660]
Welcome to FirebaseUI and thanks for submitting an issue!

Please take a look at [open issues](https://github.com/firebase/FirebaseUI-Android/issues?q=is%3Aopen+is%3Aissue), as well as [resolved issues](https://github.com/firebase/FirebaseUI-Android/issues?q=is%3Aissue+is%3Aclosed), to see if your issue is either already being addressed, or has been solved by someone else.

If not, please feel free to fill in the following info so we can help faster!

### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a GitHub issue.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.
  * For general Firebase discussion, use the [firebase-talk google group](https://groups.google.com/forum/#!forum/firebase-talk)
  * For help troubleshooting your application that does not fall under one of the above categories, reach out to the [personalized Firebase support channel](https://firebase.google.com/support/contact/troubleshooting/)

### Step 2: Describe your environment

  * Android device: Asus Zenfone 2
  * Android OS version: 6.0.1
  * Google Play Services version: 3.9.08
  * Firebase/Play Services SDK version: 10.2.1
  * FirebaseUI version: 1.2.0
  
### Step 3: Describe the problem:
Login with email and google work fine. When i'm trying to login with facebook everything goes well (login in facebook app, accept base permissions) untile I come back to AuthUi page where I get the following error:
```
[...]W/AuthMethodPicker: Firebase sign in with credential unsuccessful
       com.google.firebase.FirebaseException: An internal error has occurred. [ Unsuccessful debug_token response from Facebook ]
       at com.google.android.gms.internal.zzblv.zzce(Unknown Source)
       at com.google.android.gms.internal.zzbls$zzj.zza(Unknown Source)
       at com.google.android.gms.internal.zzbmd.zzcf(Unknown Source)
       at com.google.android.gms.internal.zzbmd$zza.onFailure(Unknown Source)
       at com.google.android.gms.internal.zzbly$zza.onTransact(Unknown Source)
       at android.os.Binder.execTransact(Binder.java:453)
[...]E/CredentialSignInHandler: Unexpected exception when signing in with credential
       com.google.firebase.FirebaseException: An internal error has occurred. [ Unsuccessful debug_token response from Facebook ]
       at com.google.android.gms.internal.zzblv.zzce(Unknown Source)
       at com.google.android.gms.internal.zzbls$zzj.zza(Unknown Source)
       at com.google.android.gms.internal.zzbmd.zzcf(Unknown Source)
       at com.google.android.gms.internal.zzbmd$zza.onFailure(Unknown Source)
       at com.google.android.gms.internal.zzbly$zza.onTransact(Unknown Source)
       at android.os.Binder.execTransact(Binder.java:453)
```

#### Observed Results:

  I've double checked the facebook app configuration, I'm using the right package (I've taken it from the AndroidManifest, as className I'm using "com.firebase.ui.auth.AuthUI" (I've tried also with the Activity that start the AuthUI istance), the hash key is good (The facebook login flow goes fine until the end)
  
#### Expected Results:
   Sign in user with facebook

#### Relevant Code:

  ```
  startActivityForResult(
                            AuthUI.getInstance()
                                    .createSignInIntentBuilder()
                                    .setIsSmartLockEnabled(!BuildConfig.DEBUG)
                                    .setProviders(Arrays.asList(new AuthUI.IdpConfig.Builder(AuthUI.EMAIL_PROVIDER).build(),
                                            new AuthUI.IdpConfig.Builder(AuthUI.GOOGLE_PROVIDER).build(),
                                            new AuthUI.IdpConfig.Builder(AuthUI.FACEBOOK_PROVIDER).build()))
                                    .build(),
                            RC_SIGN_IN);
  ```

**Comment by SUPERCILEX** [comment]
@Utnapishtim86 Do you have this part setup?
![image](https://cloud.githubusercontent.com/assets/9490724/25417050/32649958-29f6-11e7-968c-0c887e56a040.png)

Your issue might also be related to https://github.com/firebase/FirebaseUI-Android/issues/526#issuecomment-274307114.

**Comment by samtstern** [comment]
@Utnapishtim86 thanks for this report, is this still happening to you?

I have also filed a bug internally to get a better error message in the future as "Unsuccessful debug_token response from Facebook" is not very helpful!

**Comment by Utnapishtim86** [comment]
Hi, I'll look into it tomorrow. It's for a side project I've been busy these days. I will report back. 
Thanks for the support.

**Comment by Talor-A** [comment]
Hi any update on this? I'm having the same issue unfortunately...

**Comment by ArtworkAD** [comment]
Double check app-id/app-secret in firebase console. In my case I got the same error message with a wrong app-secret

**Comment by jubby2000** [comment]
+1, I have the same issue. Verified the id and secret. I get the Facebook account chooser, but then I get the web screen saying that the hash is incorrect. Based on Facebook's instructions it can't possibly be any other hash.

https://goo.gl/photos/MddqDSJqArQxB76y5

**Comment by jubby2000** [comment]
Solved it using this: https://stackoverflow.com/questions/23674131/android-facebook-integration-invalid-key-hash

**Comment by Kottidev** [comment]
@jubby2000 in wich response it solved .

**Comment by jubby2000** [comment]
@Kottidev this is what I did:
Took this out of the Gradle file:
`compile 'com.facebook.android:facebook-android-sdk:[4,5)'`

Included this in the manifest under the application tag:
```
<meta-data
android:name="com.facebook.sdk.ApplicationId"
tools:replace="android:value"
android:value="@string/facebook_app_id" />
```

**Comment by epileftro85** [comment]
+1 for review the app ID and app Secret

**Comment by agentraymond232** [comment]
Any fixes to this?

**Comment by judacribz** [comment]
I have this same error. Everything i correct in terms of app secret and app id. It works when I make my own app on the facebook developer page. But when I switch to another facebook app on that page. Which I am an admin of plus another person. She can log in with her facebook. But I cannot. We have the same code.

**Comment by SUPERCILEX** [comment]
@samtstern I think this issue can be closed since it seems to be a misconfiguration from the Facebook dev console.

**Comment by hErBiDoY** [comment]
@SUPERCILEX... this issue is not a misconfiguration from Facebook Dev console.

I also have this same error with Facebook, Twitter Sign-In and Email Sign in, using FirebaseAuth.

I have countlessly rechecked my App ID and App secret in both Facebook and Twitter developer console, as well as in Firebase Console... but I am yet to make headway with this error .... and it is frustrating.

...still the same FirebaseNetworkException error!

**Comment by SUPERCILEX** [comment]
@hErBiDoY did you configure the SHA1 hash in Firebase Console? If all the providers are failing, then it's unlikely to be related to Facebook.

**Comment by hErBiDoY** [comment]
@SUPERCILEX... Yes, my debug SHA1 hash is configured in Firebase console; and 'Google Sign in' has always been successful.
I only have issues with the other providers (Facebook, Twitter) and email.

**Comment by SUPERCILEX** [comment]
Have you [configured everything correctly](https://github.com/firebase/FirebaseUI-Android/blob/master/auth/README.md#identity-provider-configuration)?

**Comment by IshanNaktode** [comment]
Hi **@SUPERCILEX** I am facing the same issue and I did some investigation, reporting to facebook and followed the checks. In my case, I am getting an app invalid/deleted error from firebase(via facebook). On reporting the issue, I learnt that the error originates from google identity toolkit as it provides an invalid App ID to facebook.

As I said earlier, I did check that everything is configured properly (App ID, App secret and OAuth Redirect URIs), but still I am getting the error! Although, I have a potentially useful bit of information I can provide you.

I had previously linked a FB app with firebase which later on I deleted (but hey, it was working well, super smooth)! Then, I created a new one, and linked the new one with firebase, and I did make sure everything is configured properly. Ever since then, I get this error - 

Unsuccessful debug_token response from Facebook:
```
{ 
  "error": { 
    "message" : "Error validating application. Application has been deleted." , 
    "type" : "OAuthException",
    "code":190, 
    "fbtrace_id": "BBVR+XUEpfn"
  }
}
```

I hope this helps you solve the issue.

**Comment by Asad-Kabir** [comment]
Error: [auth/invalid-credential] The supplied auth credential is malformed or has expired. [ Unsuccessful debug_token response from
Facebook:

**Comment by malcolmdeck** [comment]
This issue is almost always a configuration issue - the error means that Facebook doesn't trust your application for some reason, so it's a little hard for us to pin down, but let us know if the above comment chain doesn't have an answer that solves your problem, then I need some more information to help debug here:

1. Can you please tell us more information about the version of FirebaseUI you're using?
2. Can you please validate that your SHA1 and packageName are correctly registered?
3. Can you confirm that your registration in the Facebook console is correct?
