### ISSUE TITLE
Distinguish between register/login for backend server auth validation

### ISSUE THREAD

**Issue by AndroidRio** [firebase/FirebaseUI-Android#671]
### Step 3: Describe the problem:
My request is quite simple. A feature to distinguish between login/register in FirebaseUI so I can go to different endpoints in my backend depending on which situation happened.

**Comment by SUPERCILEX** [comment]
@AndroidRio This feature has been requested several times, but it hasn't been done because it's relatively difficult to implement on the FirebaseUI side. The simple solution usually mentioned is store user info in your backend and then check if there is any data for the given uid. If not, then it's a new user. Otherwise, it's an existing one. Hope this helps! 😄

**Comment by shanukag** [comment]
@SUPERCILEX I have the same issue as @AndroidRio, but how can i save the UID if the user object is null when starting the signinintent?

**Comment by SUPERCILEX** [comment]
@shanukag Take a look at how to [handle the sign-in response](https://github.com/firebase/FirebaseUI-Android/tree/master/auth#handling-the-sign-in-response). You can also register an [AuthStateListener](https://firebase.google.com/docs/reference/android/com/google/firebase/auth/FirebaseAuth.html#addAuthStateListener(com.google.firebase.auth.FirebaseAuth.AuthStateListener)). In both cases, that's where you'll want to [get the currently signed-in user](https://firebase.google.com/docs/auth/android/manage-users#get_the_currently_signed-in_user). Hope this helps! 😄

**Comment by AndroidRio** [comment]
Thanks for the support!

**Comment by samtstern** [comment]
FYI the new `FirebaseUserMetadata` class should help with this:
https://firebase.google.com/docs/reference/android/com/google/firebase/auth/FirebaseUserMetadata
