### ISSUE TITLE
Why do you write this WARNING below without suggesting a solution? 

### ISSUE THREAD

**Issue by erikswed** [firebase/FirebaseUI-Android#683]
Below is a warning to not use Twitter Consumer Key and Consumer Secret but no directions or suggestions into how to surcomvent this obviously totally bad state.

    > 
>     <string name="twitter_consumer_key" translatable="false">CHANGE-ME</string>
> 
>     
>     <string name="twitter_consumer_secret" translatable="false">CHANGE-ME</string>

**Comment by samtstern** [comment]
@erikswed see this comment from a member of the Fabric team:
https://github.com/firebase/FirebaseUI-Android/issues/269#issuecomment-286525252

Leaving the key in the app is not catastrophic because Twitter understands that most people do this and has built their security model around it.  That warning is there to explain the risks involved, as we want people to be conscious of the action.

In general I am going to close this issue as the discussion in #269 is probably a duplicate.  Thanks for taking the time to ask!

**Comment by erikswed** [comment]
Can you expand on this? "Leaving the key in the app is not catastrophic because Twitter understands that most people do this and has built their security model around it"
Link?
Source?

**Comment by samtstern** [comment]
This link from my previous comment is the source:
https://github.com/firebase/FirebaseUI-Android/issues/269#issuecomment-286525252
