### ISSUE TITLE
SmartLock offered to save my password even when I had SmartLock disabled

### ISSUE THREAD

**Issue by samtstern** [firebase/FirebaseUI-Android#709]
### Step 2: Describe your environment

`version-2.0.0-dev`
  
#### Steps to reproduce:

  1. Email sign in, smartlock disabled
  2. Existing account
  3. Enter password
  
#### Observed Results:

  * Offered to save my password with SmartLock
  
#### Expected Results:

  * Don;'t offer to save
  
#### Relevant Code:

`none`

**Comment by SUPERCILEX** [comment]
@samtstern Hmmm, I can't repro this one. I don't think it's even possible unless `FlowParameters` or the support library has some really funky bug since we are guaranteed to check if Smart Lock is disabled before starting the request: https://github.com/firebase/FirebaseUI-Android/blob/version-2.0.0-dev/auth/src/main/java/com/firebase/ui/auth/util/signincontainer/SaveSmartLock.java#L206-L209.

Maybe try again or clear the app data? It's probably some left over state or something.

**Comment by samtstern** [comment]
@SUPERCILEX yeah I can't repro either ... maybe I was just tired and enabled smartlock by accident.
