### ISSUE TITLE
Support partial updates to the viewholder using payloads. 

### ISSUE THREAD

**Issue by gatorboy** [firebase/FirebaseUI-Android#713]
Currently, `onBindViewHolder` uses no payload to support the diff updates to the view holder. I would like to use the overloaded method of `onBindViewHolder` that has `List<Object> payloads` parameter which contains the old `DataSnapshot` value for the end client to use for partial updates. Could you please let me know if this is a desired change so that I can PR?

**Comment by SUPERCILEX** [comment]
@gatorboy I hadn't heard of payloads before (yay to learning something new! 😄), but my main concern is that we won't be doing it right. The point of payloads is to do a partial update to the `ViewHolder` right? Unfortunately, we don't have the previous `DataSnapshot`, only the new one which devs can get anyway from the normal `onBindViewHolder` if they like. I feel like adding a payload might be misleading so I would rather let the client override `onChildChanged` and let them figure out their own diffs. However, this is @samtstern's call since I'm not the repo owner.

**Comment by samtstern** [comment]
@gatorboy thanks for the FR.  @SUPERCILEX is right though, we don't keep the old `DataSnapshot` around so we can't support this without a major overhaul.  I think this is something that would be better developed in a fork of your own.  If you do it, let us know!

**Comment by gatorboy** [comment]
Thank you @SUPERCILEX & @samtstern 

Right, this is to partially update the viewholder. Probably helpful avoiding redraw of all the views in a complex view holder.

I wrote this simple change in my fork to support this functionality. Let me know what you think.
https://github.com/gatorboy/FirebaseUI-Android/commit/cb15fd483f88b4a1196fc332f002f2e124c4c4bd

**Comment by martipello** [comment]
so he wrote it and he let you know, it looks good to me, was this ever added to the lib?
