### ISSUE TITLE
I/O 2017 TODO list

### ISSUE THREAD

**Issue by SUPERCILEX** [firebase/FirebaseUI-Android#721]
@samtstern I really wish I could have been at I/O, there were so many awesome announcements!!! 😄 I've made a list of stuff I think we should do with the new I/O stuff:
1. (#716) Phone auth! I can't wait to see that one come out!!! @samtstern Are you guys planning on submitting a PR or adding the commits to the dev branch directly? I'd love to help out if possible! 😄 
1. (#718) On the database side, I definitely think supporting the architecture components would really cool! Not having to constantly add and remove the db listeners on config change will be a cool perf boost.
1. **Kotlin!** I've been playing around with the language for a bit and I really like it! (I think that's pretty much everyone's opinion at this point 😆) I think we should try as a soft policy to add all new files in Kotlin. What do you think? If you agree, I'll submit a PR (once phone auth has been implemented to minimize conflicts) that adds Kotlin support and converts a few small internal classes to Kotlin so we can dip our feet in the waters. As I go I'll be happy to explain stuff if you haven't played around with Kotlin yet. (Extension functions are the best!)

@samtstern Thoughts, comments, concerns, random outbursts on the stuff above? 😄

**Comment by samtstern** [comment]
1. For phone auth we have been working on an internal branch since we're dependent on a Play services SDK that is not out yet.  As soon as that comes out we will convert the phone auth work to a PR.

2. I agree, this will be a cool addition.

3. Let's wait a little on Kotlin, I have absolutely no idea what the mechanics of shipping a Kotlin library are or what community expectations will be.  I do want to use some [Java 8 language features](https://developer.android.com/studio/preview/features/java8-support.html) though.

**Comment by SUPERCILEX** [comment]
1. Awesome!
1. 😎!
1. Ah yeah, I didn't think about that. 😕 I'll have to play around with including FirebaseUI into a Java only project. As for Java 8, I have a PR waiting but robolectric is broken with the 2.4+ Gradle plugin. 😢 I'll have to try the 3.0 one. Hopefully it will work! 😀

Closing since you answered all of my questions. Thanks!
