### ISSUE TITLE
Glide 4.0 support?

### ISSUE THREAD

**Issue by wonsuc** [firebase/FirebaseUI-Android#731]
Glide is now v4.0.0-RC0.

Since FirebaseUI is using 3.7 version, [StreamModelLoader and using method has been changed or removed on v4.0.](http://bumptech.github.io/glide/doc/migrating.html#using-modelloader-streammodelloader)

Is there any plan to migrate and support for Glide v4.0? Or FirebaseUI project will continue with v3.7 for a while?

Thanks!

**Comment by samtstern** [comment]
@wonsuc thanks for the link!  To be honest I had not seen Glide 4.0 yet, looks like we should be able to make the update without too much work, although I don't think it will make it into the next FirebaseUI release.

**Comment by guilmarc** [comment]
@samtstern  Will the new Glide version be supported in future or must we continue with 3.8 ?

Thanks.

**Comment by samtstern** [comment]
@guilmarc we definitely want to support it in the future but I also want to make sure we can keep backwards compatibility.  I will look into this.

**Comment by puf** [comment]
Also see: https://stackoverflow.com/questions/44949432/how-to-integrate-firebase-with-glide-using-method

**Comment by samtstern** [comment]
Since gradle won't let me have two versions of one dependency (even if they're `provided`) there's no way to do this without a breaking change to `FirebaseUI` which means waiting for the next major version.

I think I have written all the necessary code in #802 though.  So those who are very eager could build from that branch (or just copy out the `Loader` class).

**Comment by samtstern** [comment]
Version 3.0 has been released!

**Comment by PeterHdd** [comment]
According to this http://bumptech.github.io/glide/doc/migrating.html#using, using() was removed from Glide 4.
