### ISSUE TITLE
Phone auth - the custom token corresponds to a different audience

### ISSUE THREAD

**Issue by vladgheorghe** [firebase/FirebaseUI-Android#759]
Greetings, I have implemented the new phone authentication feature and followed all of the required steps. However, after I submit my phone number I receive a dialog with the following message "The custom token corresponds to a different audience". Any help would be greatly appreciated as I intend on migrating from digits asap.

**Comment by samtstern** [comment]
@vladgheorghe are you seeing this with FirebaseUI or when implementing phone authentication yourself?  Can you show me a screenshot?

**Comment by vladgheorghe** [comment]
@samtstern with FirebaseUI, I have enabled phone auth on  firebase console and also checked project settings and google-service.json

gradle
```
    compile 'com.google.firebase:firebase-core:11.0.1'
    compile 'com.google.firebase:firebase-messaging:11.0.1'
    compile 'com.google.firebase:firebase-auth:11.0.1'
    compile 'com.firebaseui:firebase-ui-auth:2.0.1'
```
manifest
```
<service
            android:name=".networking.push.FirebaseIDService">
            <intent-filter>
                <action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
            </intent-filter>
        </service>

        <service
            android:name=".networking.push.FirebaseService">
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT"/>
            </intent-filter>
        </service>

        <meta-data
            android:name="com.facebook.sdk.ApplicationId"
            android:value="@string/facebook_app_id"
            tools:replace="android:value"/>

        <meta-data
            android:name="io.fabric.ApiKey"
            android:value="hidden_for_this_comment"
            tools:replace="android:value"/>

        <meta-data
            android:name="com.google.android.gms.version"
            android:value="@integer/google_play_services_version" />

```
code

```
  startActivityForResult(
                            AuthUI.getInstance()
                                    .createSignInIntentBuilder()
                                    .setProviders(Arrays.asList(
                                            new AuthUI.IdpConfig.Builder(AuthUI.PHONE_VERIFICATION_PROVIDER).build()
                                    ))
                                    .setTheme(R.style.DigitsTheme)
                                    .build(),
                            FIREBASE_SIGN_IN);
```





![device-2017-06-17-021453](https://user-images.githubusercontent.com/13194727/27247591-cd387258-5302-11e7-938a-c52d0eaf45f7.png)

**Comment by samtstern** [comment]
cc @ashwinraghav any idea about this error message?

**Comment by bareq** [comment]
I had a same issue. I had to add SHA-1 hash to project settings. You can add debug hash for example by execute: `keytool -list -v -keystore .android/debug.keystore` in your user directory.

**Comment by samtstern** [comment]
@bareq thanks for pointing that out.  @vladgheorghe have you added a SHA1 for your app in the Firebase console?

**Comment by Gubbi** [comment]
Facing the same issue. SHA-1 hash has been added to project settings.

**Comment by prazjain** [comment]
same issue here, I am implementing phone authentication myself on android.

**Comment by samtstern** [comment]
In FirebaseUI `2.1.0` we updated the error message for this to be clearer.  The backend team has informed me that this error should only come from a developer configuration issue such as incorrect SHA1 or an API key from a different project.

The backend team has also promised to start returning better error messages for this in the future.  In the meantime if you are stuck on this issue please contact Firebase Support who can better help debug (they can dig into your project config).

**Comment by tigerpup** [comment]
Hi I m Facing the same issue , I have also added my SHA key and downloaded and readded the google-services.json.  I m using a library module to perform all Firebase action. I only face this issue with with Authentication features while all other features like Firestore,FireStorage are working perfectly fine.
My Library module obviously has a  different package name , so I thought it may be due to that but I checked the options with which the default FirebaseApp was loaded right before I called PhoneAuthProvider authProvider's getInstance() Method like this 

`public void AuthenticateUsingPhoneNumber(String phone, Activity authenticationActivity, PhoneAuthProvider.OnVerificationStateChangedCallbacks callbacks){
 Log.i(TAG,"App Unique name"+ FirebaseApp.getInstance().getOptions());
PhoneAuthProvider authProvider=PhoneAuthProvider.getInstance(FirebaseAuth.getInstance());
        authProvider.verifyPhoneNumber(
                phone,
                60, //Timeout duration
                TimeUnit.SECONDS,
                authenticationActivity,
                callbacks
        );
    }`

As I coudn't find a way to know the project PhoneAuthProvider was using I made sure it used the FirebaseAuth for the default project for which I know the options. The Options correspond to the options for my Library module where the above method is defined. I faced a similar problem when I was doing google Authentication which I solved by whitelisting the WebAPI for my app project in my module's firebase project. But this seems to be a different problem all together. 

P.S Also Is there a way to confirm the package FirebaseAuth is using at any given time??
