### ISSUE TITLE
"Cannot resolve method using[...]"

### ISSUE THREAD

**Issue by PLPellegrini** [firebase/FirebaseUI-Android#783]
https://stackoverflow.com/questions/44832599/cannot-resolve-method-usingcom-firebase-ui-storage-images-firebaseimageloader

I'm having the same problem on my end. It tells me nothing more than 
"Cannot resolve method using(com.ui.firebase.storage.images.FirebaseImageLoader)". 
Everything else seems to be working fine.

  * FirebaseUI version: 1.2.0
  * Glide version: 4.0.0-RC1

**Comment by TheCraftKid** [comment]
It appears this library is using the 3.x version of Glide, and you're using the newer 4.0.0 branch. We need to update the version used in FirebaseUI-Android, but for now, you'll have to use version 3.

@SUPERCILEX Are we down for a PR?

**Comment by SUPERCILEX** [comment]
@TheCraftKid you can give it a shot, but I think it'll take far more effort than simply changing the version number. I upgraded my app to Glide 4.0 and they have a [new module system](http://bumptech.github.io/glide/doc/generatedapi.html) that uses annotations and does a bunch of crazy stuff to extend the Glide builder. Because of that
1. We'll have to [migrate away from `using`](http://bumptech.github.io/glide/doc/migrating.html#using)
2. I dunno how it's going to work out in terms of backwards compatibility

Do give it a shot though! 😄 

FYI: this is a dup of #731.

**Comment by samtstern** [comment]
@TheCraftKid the big issue is backwards compatibility if we want to make it into the `2.1` release.  Otherwise we need to wait for a major version, and I don't think we should do that again too soon since `2.0` is so fresh.

**Comment by samtstern** [comment]
As @SUPERCILEX said, closing as a dup of #731

**Comment by sgatade** [comment]
Dear all,

Following
[Git Wiki for Storage](https://github.com/firebase/FirebaseUI-Android/blob/master/storage/README.md)

**Dependencies**     
compile 'com.firebaseui:firebase-ui-storage:3.1.0'
compile 'com.github.bumptech.glide:glide:4.1.1'
annotationProcessor 'com.github.bumptech.glide:compiler:4.1.1'

In `MyAppGlideModule`, on the following line...

`registry.append(StorageReference.class, InputStream.class,
                new FirebaseImageLoader.Factory());`

I'm getting **Cannot Resolve Symbol** on **Factory()**. Screenshot below...

![image](https://user-images.githubusercontent.com/13362030/33172777-7b56e9f4-d077-11e7-8344-4e3e9002fde2.png)

I checked the source code and the Inner Static class Factory is present in the code.

What could be wrong? I'm stuck and cannot complete the Image Download part, so any help would be appreciated!

Thanks in advance...

SG
