### ISSUE TITLE
No User Name for Email Authentication

### ISSUE THREAD

**Issue by LeeHounshell** [firebase/FirebaseUI-Android#792]
### Step 2: Describe your environment

  * Android device: _____Nvidia Shield Tablet
  * Android OS version: _____Marshmallow
  * Google Play Services version: _____25.4.0
  * Firebase/Play Services SDK version: _____11.0.1
  * FirebaseUI version: ____2.0.1
  
### Step 3: Describe the problem:
Unable to get User Name after new email login.

#### Steps to reproduce:

  1. _____add code to get the new user info:
        mAuthStateListener = new FirebaseAuth.AuthStateListener() {
            @Override
            public void onAuthStateChanged(@NonNull FirebaseAuth firebaseAuth) {
                FirebaseUser user = firebaseAuth.getCurrentUser();
                LogHelper.v(TAG, "---> onAuthStateChanged: user=" + user.getDisplayName() + ", email=" + user.getEmail() + ", provider=" + user.getProviderId());
            }

  2. _____run the FirebaseUi app; create a new user; enter a User Name for that user.

#### Observed Results:

  3. _____notice that the User Name is always null, even if a proper name is input.

**Comment by LeeHounshell** [comment]
issue happens during user creation only.  subsequent logins have the user name ok.

**Comment by samtstern** [comment]
@LeeHounshell I think this is actually working as intended.  I understand why it's not ideal but there's nothing FirebaseUI can do about it for now.

If you look at the code for how we register a user:
https://github.com/firebase/FirebaseUI-Android/blob/master/auth/src/main/java/com/firebase/ui/auth/ui/email/RegisterEmailFragment.java#L213

We create a new account with email and password.  Then when that operation is done, we issue a user profile change request to add the name.

The problem is that your `AuthStateListener` fires after the user account is created (that's when the auth state changes).  The change to the user's name does not fire your listener.

You may be able to use an `IdTokenListener` (I believe those fire on user information changes).  The best thing to do though is not to use a listener for FirebaseUI sign up and instead call `getCurrentUser` when the flow is over.

**Comment by LeeHounshell** [comment]
unfortunately those solutions don't work for me.  I need to determine the
user name (just entered via Text Edit in the FirebaseUI auth) at the time I
get a callback for the user being signed in.

without that i am either forced to build lots of unnecessary code and a
state-machine to manage user names, or else re-prompt "Choose a User Name"
to get the info i need at the time i need it.
in the interest of API friendliness, perhaps you can just allow delaying
the callback until you have all the user information (including User Name)?

**Comment by samtstern** [comment]
@LeeHounshell by the time the FirebaseUI flow completes (and you get `onActivityResult`) you will have the complete user.  Listening to the callback is not advisable, you're reacting to FirebaseUI before FirebaseUI has finished the full flow.

There's no way we can "delay the callback" as the callback is designed to tell you when the user signs in or signs out, which it does.  Name changing is not one of those events.

**Comment by LeeHounshell** [comment]
FYI, i have not been able to get the user display name in onActivityResult
for case of new email user just created.  it returns null.

a working example would be most appreciated for us dummies.

**Comment by samtstern** [comment]
I just ran the example app (provided in this repo) and added the following lines inside onActivityResult:

```java
if (resultCode == ResultCodes.OK) {
    Log.d("USERNAME", FirebaseAuth.getInstance().getCurrentUser().getDisplayName())
}
```

After going through the new email flow and signing up a new user with a display name I see the user name I expect.  Do you get a different result?

**Comment by LeeHounshell** [comment]
Thanks Sam, that helped.  I was able to solve the problem in my code.

**Comment by samtstern** [comment]
@LeeHounshell glad to hear it!
