### ISSUE TITLE
name of resources

### ISSUE THREAD

**Issue by OlegTarashkevich** [firebase/FirebaseUI-Android#794]
Please change all names of resources.

For example:
    `<string name="done" translation_description="Progress dialog success transition once sms is sent">Done</string>`

has name "done". In my projects I using the same name with another content.
Please change all resource names according library pattern. 
For example: "firebase_ui_done"
    `<string name="firebase_ui_done" translation_description="Progress dialog success transition once sms is sent">Done</string>`

**Comment by SUPERCILEX** [comment]
@OlegTarashkevich yeah, that's actually a really good idea, dunno why no one thought if it before! 😀 However, I think we should abbreviate to `fui_foobar` for readability's sake.

**Comment by TheCraftKid** [comment]
We should probably use a resourcePrefix in the librarys' `build.gradle` files and use the `fui_` prefix.

**Comment by samtstern** [comment]
Yep @TheCraftKid is exactly right, `resourcePrefix` is the right thing to use here.

This is not going to make the custom themers very happy!  But that's why we always say resource IDs are not part of the public API.

**Comment by samtstern** [comment]
@TheCraftKid any interest in sending a PR for this one?

**Comment by TheCraftKid** [comment]
Yep, give me a minute.

**Comment by TheCraftKid** [comment]
Wow, that was more annoying than I thought it would be. Probably should have written a Python script or something, but I want to confirm that not changing the `colorPrimary`, `colorPrimaryDark`, and `colorAccent` was the correct decision for library usage.

**Comment by samtstern** [comment]
Yeah @SUPERCILEX can elaborate but we want to keep those the same since we're deliberately leaning on `AppCompat`.

**Comment by SUPERCILEX** [comment]
@TheCraftKid yeah, happy to elaborate! 😀 You can see what we did in #696, but basically we purposefully want people to override those colors knowingly or not. AppComat does some magic behind the scenes so that when you use their style, they apply those colors to your buttons, edittexts, etc without any effort or customization required from the developer. That means someone can drop FirebaseUI into their app and as long as they use AppComat, the login screens will automagically theme themselves to the app's look and feel. (Basically, I got lazy and didn't want to figure how to properly override the FirebaseUI theme. 😂)

**Comment by samtstern** [comment]
This has been fixed and we released version `2.1.1`.
