### ISSUE TITLE
Problem sign-out from Facebook provider

### ISSUE THREAD

**Issue by juan-pablo-giron** [firebase/FirebaseUI-Android#800]
Good afternoon, 

I am trying to create an application where the aunthentication phase is made using Firebase UI. Actually, I am using Facebook, Google and Email to the authentication. The problem that I have is with facebook sign-out, actually Facebook SDK gets account information from my installed Facebook lite, so I can not choose another account to access to the App. I want (if possible) that when I am logged-out from Facebook I can see the chooser fragment  to continue with my account associated to facebook lite or change for new one.

The code for sign-out from facebook is next:

```java
public boolean onOptionsItemSelected(MenuItem item) {
        switch (item.getItemId()){
            case R.id.logout_menu:
                AuthUI.getInstance().signOut(this);

                if (LoginManager.getInstance() != null){
                    LoginManager.getInstance().logOut();
                }

                Intent mIntent = new Intent(getApplicationContext(), LoginActivity.class);
                startActivity(mIntent);
                finish();

                return true;
            default:
                return super.onOptionsItemSelected(item);
        }
    }
```

thank you in advanced.

**Comment by SUPERCILEX** [comment]
@juan-pablo-giron I don't think this is possible because of how the Facebook SDK works: we don't choose what method Facebook picks to authenticate the user, and it seems like they default to the app if it's installed. I'm guessing you could sign out of Facebook in the app and then it would work? Basically, I don't think Facebook expects users to have several different accounts.

@samtstern I believe this issue can be closed given the explanation above.

**Comment by samtstern** [comment]
I believe @SUPERCILEX is correct, which is unfortunate but there's nothing we can do on our side.
