### ISSUE TITLE
FirebaseLoginDialog cancel

### ISSUE THREAD

**Issue by abond** [firebase/FirebaseUI-Android#82]
If user cancel FirebaseLoginDialog nothing is happen and application gets into unfunctional state.
Maybe dialog should be uncancelable or it should call onFirebaseLoginUserError() ?

**Comment by puf** [comment]
What do you mean by "cancel"? In the demo app, I just tried:

- tapping outside of the dialog
- pressing the back button

And both leave the app functioning normally.

**Comment by abond** [comment]
Sorry, of course what is unfunctional in my case can be normal in others!

I assume that my app can't function well if there is no authenticated user.
So I need some means to handle the situation where user refused to log in (or accidentally tapp outside of the dialog or press the back button).
Now if user choose to log in with any provider (except PASSWORD obviously) and then press back button, we can handle it in onFirebaseLoginUserError method. But there is no way to handle the situation when user cancel FirebaseLoginDialog.

**Comment by puf** [comment]
Ah, got it. It is indeed one of the use-cases we want to cater for.

For the moment, how about having a LoginActivity with a single "Sign in"
button that simply only starts the MainActivity in onFirebaseLoggedIn?

Alternatively, you'll could take the logic from the LoginDialog and
replicate that in your own LoginActivity (so that the AlertDialog is not
needed anymore).

**Comment by abond** [comment]
Thank you for workarounds!
I use one for now. But I hope this will be solved in near future.
