### ISSUE TITLE
Merging of facebook and gmail account doesn't work as expecting

### ISSUE THREAD

**Issue by flavio20002** [firebase/FirebaseUI-Android#838]
Good evening every one.
I've found a abnormal behaviour regarding the "merging" of authentication provider.
These are the step to replicate the behaviour :

1.  Login with Facebook
2. Logout and login with google provider. This is going to replace the Facebook provider instead of merging them. if you go on firebase console you will see only google icon.
3. If you logout and try to login with facebook provider you will get an error, inviting you to login via Google. If you click the sign in button, you will find out that the picture account is indeed the facebook one, and now on Firebase console the account are merged. Both google and facebook icon are present.
4. if you logout and log in with facebook it works without errors
5. if you logout and log in with google it works without errors

It is a bug, right?

Thanks.

Flavio

**Comment by SUPERCILEX** [comment]
@flavio20002 Kind of, the Google provider gets special treatment because Firebase is a Google product (surprise! 😆). So basically, Firebase auth always tries to upgrade accounts to Google thus minimizing user interactions. As you saw with Facebook/Twitter, there was an extra step that wasn't there with the Google sign-in. In FirebaseUI, we don't give any provider special treatment so that's backend stuff we don't control.

However, if you want full account linking support I've got a fork of FirebaseUI that will help you with that. The PR is #309 and here are some [install instructions](https://github.com/firebase/FirebaseUI-Android/issues/123#issuecomment-316268664) + [extra info](https://github.com/firebase/FirebaseUI-Android/issues/123#issuecomment-317343123).

**Comment by flavio20002** [comment]
It is strange, however. I would expect the google account replace the facebook one and giving always error when trying to login with facebook, not "trying to replace", getting an error only the first time and then coexist.

**Comment by samtstern** [comment]
I don't think this is a bug in FirebaseUI so I am going to close this issue.  If I have misunderstood, please let me know.

**Comment by INTISSAR1998** [comment]
did anyone here can give me the code ?
