### ISSUE TITLE
[Discuss] Separate component versioning

### ISSUE THREAD

**Issue by samtstern** [firebase/FirebaseUI-Android#875]
Right now all `firebase-ui-{foo}` modules are versioned together.  As the rates of change of the modules continue to diverge, this makes less and less sense.  I think we should change the model such that each module has its own version number, which we can update semantically (semver.org).

We can either remove the combined `firebase-ui` target, or set its version number to the maximum of all other modules.

Pros:
  * Stable modules don't see needless version updates
 
Cons:
  * Harder to discuss version numbers when debugging issues
  * Need to remember to release patch version bumps when underlying SDKs change
  * Release branch management becomes more complicated

@puf @SUPERCILEX @TheCraftKid @morganchen12 what do you think?

**Comment by puf** [comment]
@mcdonamp Do you remember where we last had this discussion? It might be useful to dig that up to link/include here too.

@samtstern The regular Firebase Android SDK uses a single version for all modules. How does module versioning affect them differently than FirebaseUI?

**Comment by samtstern** [comment]
We copied the model from the Firebase/Play services SDKs originally.  Their major version number tells you what major version of the service (Play services APK) it is compatible with.  And their minor versions don't differ mostly out of convenience.

We don't have a service to keep up with.  But, we do have a dependency on these underlying SDKs and if we moved to separate versions we would have to tell our developers not to mix different FirebaseUI versions in the same app because of transitive dependency collisions.

**Comment by krisu7** [comment]
I think we should keep current versioning to be consistent with underlying Firebase Android SDK. People usually use auth with other modules so it is easy to maintain single version under one variable.

**Comment by SUPERCILEX** [comment]
Oh, @krisu7 brings up a good point. I was going to say that separate versioning makes sense, but then the whole finding the right version issue comes up. I think it would make things really messy for people looking for the latest version of X module.

So that would be my only concern, making it easy for devs to find the right version of whatever module they're looking to import.

**Comment by samtstern** [comment]
Yeah the more I think about it the less I like my original idea to use flexible versions...

**Comment by TheCraftKid** [comment]
I'm thinking we let the library use its own versions and force devs to explicitly define their own versions if that's a possibility. Because of the new `api` and `implementation` Gradle build options, wouldn't we be able to use separate versions of the Play Services libraries within the library but allow developers to specify separate versions, or does the rule about conflicting Play Services version apply to that, as well?

**Comment by krisu7** [comment]
Yeah @SUPERCILEX, it is only issue I can think of atm

@TheCraftKid don't we do something similar already? Using the latest version of module and overriding play services and support dependencies?

**Comment by TheCraftKid** [comment]
@krisu7 Apparently not. I just checked the `build.gradle` files and they all use `compile`.

**Comment by SUPERCILEX** [comment]
@TheCraftKid we haven't upgraded to the 3.0 plugin yet (though that's on my TODO list).

**Comment by TheCraftKid** [comment]
@SUPERCILEX Wouldn't that solve our problem, though? Oh, wait, the 3.0 plugin isn't stable yet, right?

**Comment by samtstern** [comment]
Thanks everyone for the discussion, I think we will stay with a single version for now.
