### ISSUE TITLE
Please include the Firebase/Play Services Version in the release notes

### ISSUE THREAD

**Issue by mikejonesguy** [firebase/FirebaseUI-Android#884]
Since FirebaseUI-Android depends on specific version of Firebase/Play Services, it would be nice to include the required Firebase/Play Services version in the release notes for each release, so that we can know at a glance what's what when upgrading.

Thanks!

**Comment by SUPERCILEX** [comment]
@mikejonesguy We have a nice table [here](https://github.com/firebase/FirebaseUI-Android#compatibility-with-firebase--google-play-services-libraries) if you scroll a little. Does that work for you? AFAIK, we don't include that metadata in the release notes because you can actually [upgrade the dependency if necessary](https://github.com/firebase/FirebaseUI-Android#upgrading-dependencies) so it would be a bit of a misconception.

**Comment by mikejonesguy** [comment]
Yes, I'm aware of the table on the main page, I just thought it would be helpful to have it in in the release notes, which is where I would typically look to find that kind of info. I also read that bit about how to use disparate versions if needed.

If it you can find a way to include it in the release notes, I think it would be nice to have there. If not, the world will keep turning. ;-)

**Comment by SUPERCILEX** [comment]
@mikejonesguy True, I guess it makes sense to put a one-liner at the top. I don't actually have push access so this would be up to @samtstern...

**Comment by samtstern** [comment]
@mikejonesguy sounds like a good idea!  I will go back and update the last few.

**Comment by samtstern** [comment]
Added for every release from `2.0.0` onwards in the following format:

This version has the following notable transitive dependencies:

| Dependency               	| Version 	|
|--------------------------	|---------	|
| Firebase / Play services 	| 11.0.4  	|
| Support Library          	| 26.0.1  	|
