### ISSUE TITLE
listview reverse problem

### ISSUE THREAD

**Issue by ozican** [firebase/FirebaseUI-Android#90]
Dear Frank van Puffelen,
Your tutorial is very good thank you very much for this.
But i have a problem, i cant make reverse listview. I want to new message goes to top on the screen.. By the way, please explaine like tutorial because i dont understand.
Please help me, thank you very much again.You are the best!

**Comment by puf** [comment]
If you're using a `ListView`:

```
listView.setStackFromBottom(true);
```

For a `RecyclerView`:

```
manager.setStackFromEnd(true);
```

Note that these are basic Android questions, so are better posted (or search for) on StackOverflow.

**Comment by ahaverty** [comment]
Thank you for the direction @puf.
Apologies for digging up a closed issue, I just wanted to note in order to correctly reverse a recycler view you also need to call setReverseLayout(true) as well as calling setStackFromEnd(true).
e.g:
```
LinearLayoutManager layoutManager = new LinearLayoutManager(getActivity());
layoutManager.setReverseLayout(true);
layoutManager.setStackFromEnd(true);
recyclerView.setLayoutManager(layoutManager)
```

(Ensuring you set both before adding the layout manager to the recycler view also)
Perhaps anyone else stumbling through old stack overflow answers will see this and avoid unnecessarily calling costly queries on their firebase instances like most of the stack overflow answers suggested.

**Comment by samtstern** [comment]
@ahaverty thanks for the tip about setting the LayoutManager properties before calling `setLayoutManager`, that's explains some weird non-reproducible issues I've had in the past!

**Comment by puf** [comment]
Same here @ahaverty: thanks for excavating. :-)

Feel free to leave comments/edits on the Stack Overflow question too for
those who don't find it here.

**Comment by ivanguerra09** [comment]
@ahaverty thanks for the explanation. I was struggling to do the reverse ordering in recycler views. This was the best and simpler solution I've found.

**Comment by andrewclam1991** [comment]
@ahaverty setting both 
```
layoutManager.setReverseLayout(true);
layoutManager.setStackFromEnd(true); 
```

Does the trick for reversing the order of the list, but the user view starts at the bottom of the list instead of the top (needing to scroll-up to see the last item of the list).
