### ISSUE TITLE
There's no way to color phone field hint

### ISSUE THREAD

**Issue by charlag** [firebase/FirebaseUI-Android#910]
When using phone authentication there's no way to change color of the phone field hint. 
From the sources:
```
<style name="FirebaseUI.TextInputEditText.PhoneField">
        <item name="android:hint">@string/fui_phone_hint</item>
        <item name="android:inputType">phone</item>
        <item name="android:imeOptions">actionNext</item>
        <item name="android:paddingBottom">16dp</item>
        <item name="android:paddingTop">16dp</item>
  </style>
```
`android:textColorHint` is not present and thus is not connected to any color.

  * Android device: Xiaomi Mi5S
  * Android OS version: 7.1.2
  * Firebase/Play Services SDK version: 11.0.4
  * FirebaseUI version: 2.3.0

**Comment by SUPERCILEX** [comment]
@charlag Why would you want to _only_ change the hint text color? If you want to change the entire look and feel of the sign-in experience, make sure to use AppCompat and [define a `colorPrimary` and `colorAccent`](https://github.com/firebase/FirebaseUI-Android/tree/master/auth#ui-customization).

**Comment by charlag** [comment]
@SUPERCILEX the problem is that our login flow screens have a dark background and if the background is black the hint is simply not visible.

**Comment by SUPERCILEX** [comment]
@charlag is your entire app dark themed? If so, you should be using [AppCompat's `DayNight` theme](https://medium.com/@chrisbanes/appcompat-v23-2-daynight-d10f90c83e94) which FirebaseUI fully supports. Otherwise, I believe this example dark theme works:
https://github.com/firebase/FirebaseUI-Android/blob/9dc4c120f33d4f4acc42b2a0c2195e130e8b1076/app/src/main/res/values-v21/styles.xml#L17-L31

**Comment by samtstern** [comment]
Closing because there hasn't been a response in a while and we likely can't support this type of customization anyway,
