### ISSUE TITLE
 FirebaseRecyclerAdapter pending or sent status

### ISSUE THREAD

**Issue by andriiaveiro** [firebase/FirebaseUI-Android#917]
hey, i'm already try to search this question in stack overflow and github but i dont get the answer. 

i'm using FirebaseRecyclerAdapter with setPersistenceEnabled, all work great, but i want to know when my data in cache data phone or already sent to server, because when i call set or update with offline data, my data populate in recyclerview but not in server (wait for online to sent), i want know this state to change my viewholder based on pending or sent to server, how i do this?

https://drive.google.com/file/d/0By3rwGCwSjAgdGNuc2gtREJvU28/view?usp=sharing   (read status)
https://drive.google.com/file/d/0By3rwGCwSjAgN2QwWV8yUnBmbTg/view?usp=sharing (pending status)

Image Source : google allo sent state (double check icon(read status) and clock icon (pending status))

**Comment by samtstern** [comment]
@andriiaveiro if you use `setValue()` with `CompletionListener` the listener will only fire when the write has been acknowledged by the server:
https://firebase.google.com/docs/reference/android/com/google/firebase/database/DatabaseReference.html#setValue(java.lang.Object, com.google.firebase.database.DatabaseReference.CompletionListener)

I am closing this issue since this is not a FirebaseUI issue, you will have to create your own UI solution to keep track of completion listeners and show the UI you want.

**Comment by andriiaveiro** [comment]
thank for your advice

i setvalue message_status to pending first but in complete listener im update to sent :)
