### ISSUE TITLE
Does Firestore support Heterogeneous layouts for RecyclerView

### ISSUE THREAD

**Issue by CeJienAJPC** [firebase/FirebaseUI-Android#953]
### Step 2: Describe your environment

  * Firebase/Play Services SDK version: 11.4.2
  * FirebaseUI version: 3.0.0
  
### Step 3: Describe the problem:
There was no direct way of supporting Heterogeneous layout in RecyclerView using Firebase. Does Firestore offer to support heterogeneous layouts for RecyclerView?

Thanks

**Comment by SUPERCILEX** [comment]
@CeJienAJPC I like your fancy vocab, but what do you mean by "heterogeneous"? 😄

**Comment by jaywil311** [comment]
On Oct 7, 2017 11:01 PM, "Alex Saveau" <notifications@github.com> wrote:

@CeJienAJPC <https://github.com/cejienajpc> I like your fancy vocab, but
what do you mean by "heterogeneous"? 😄

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/firebase/FirebaseUI-Android/issues/953#issuecomment-334981469>,
or mute the thread

**Comment by CeJienAJPC** [comment]
Oh, I mean displaying the multiple ViewTypes in RecyclerViews. FirebaseRecyclerAdapter was supporting this with some minimal tweak. How about the FireStoreRecyclerAdapter? Just curious.

**Comment by SUPERCILEX** [comment]
@CeJienAJPC Oh, haha. Got it now.

Yeah, definitely! Having different view holder types is a recyclerview thing so any adapter will support them, including ours. 😄

**Comment by CeJienAJPC** [comment]
Thanks for the confirmation.
