### ISSUE TITLE
The eye icon in password field is invisible in dark theme

### ISSUE THREAD

**Issue by syrop** [firebase/FirebaseUI-Android#958]
In dark theme the eye icon next to the password field (render the password visible or invisible) is itself invisible.
![device-2017-10-09-185201](https://user-images.githubusercontent.com/19635111/31349306-fb21a93a-ad22-11e7-8d72-4f49887d985a.png)

**Comment by SUPERCILEX** [comment]
@syrop Whoops, I forgot to correctly update the dark mode toggle in the sample. See #959 and https://github.com/firebase/FirebaseUI-Android/pull/749#issuecomment-308815896 for info on how to setup dark mode in your app. We don't talk about it in the FirebaseUI README because it's an AppCompat thing, not specifically a FirebaseUI thing.

Thanks for the tip! 😄

**Comment by syrop** [comment]
Confirmed. Works well with the newest commit.
