### ISSUE TITLE
indexedQuery support for Firestore

### ISSUE THREAD

**Issue by brezinajn** [firebase/FirebaseUI-Android#970]
Hi,
are there plans to add indexedQuery or any client side join capability for Firestore?
Thanks :)

**Comment by SUPERCILEX** [comment]
@brezinajn Nope. (At least not on my side, @samtstern?) This is because you should be able to structure your data in a way that bypasses the need for joins. Try diffing this [RTDB Gist](https://gist.github.com/SUPERCILEX/72d6f78c4281a822166c7d8f9aa827d0) vs the [Firestore Gist](https://gist.github.com/SUPERCILEX/95813a9e0ff4854e3d51dbff75282aef).

**Comment by brezinajn** [comment]
Yeah, thats basically what I came up with as a replacement as well. Thanks for clarification.

**Comment by samtstern** [comment]
@brezinajn yes just to confirm we don't currently have plans to add this capability to the library for Firestore.
