### ISSUE TITLE
Firebase Storage UI: GlideApp not importable

### ISSUE THREAD

**Issue by halfbaked** [firebase/FirebaseUI-Android#971]
Hey guys, 

I had trouble referencing GlideApp in Android Studio. I got it solved but I think adding more to the documentation will help other folks who come along. The missing piece for me was to include the annotation processor by way of the gradle build file.  

     compile 'com.github.bumptech.glide:glide:4.1.1'
     annotationProcessor 'com.github.bumptech.glide:compiler:4.1.1'

I stumbled the solution in an [issue in the Glide github project](https://github.com/bumptech/glide/issues/1939). 

p.s. Firestore looks awesome - more fit for purpose than the Realtime DB. Keep up the great work!

**Comment by ahaverty** [comment]
It took me about 30 minutes to convert from v2 to v3 because of this. I think the readme could be a bit more verbose, and possibly include a link to a full example working with firebase ui v3.

For anyone else lost that comes across this issue, this might help:

1. This `MyGlideModule.java` looks like it can live anywhere within your src, and doesn't need to be called by anything (this concept in android is new to me anyway..)


```

import android.content.Context;

import com.bumptech.glide.Glide;
import com.bumptech.glide.Registry;
import com.bumptech.glide.annotation.GlideModule;
import com.bumptech.glide.module.AppGlideModule;
import com.firebase.ui.storage.images.FirebaseImageLoader;
import com.google.firebase.storage.StorageReference;

import java.io.InputStream;

/**
 * Glide module to register {@link com.firebase.ui.storage.images.FirebaseImageLoader}.
 * See: http://bumptech.github.io/glide/doc/generatedapi.html
 */
@GlideModule
public class MyGlideModule extends AppGlideModule {

    @Override
    public void registerComponents(Context context, Glide glide, Registry registry) {
        // Register FirebaseImageLoader to handle StorageReference
        registry.append(StorageReference.class, InputStream.class,
                new FirebaseImageLoader.Factory());
    }

}
```

And the full list of Glide dependencies:
```
    compile 'com.github.bumptech.glide:glide:4.3.1'
    compile 'com.github.bumptech.glide:annotations:4.3.1'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.3.1'
```

Once that's in, if you're seeing issues, try a project clean. You might also have some work to do on the Glide calls. The above Glide module seems to remove the need for the .with() from firebase ui v2 (It looks like Glide v4 has changed it's builder functions to use .apply()).

**Comment by samtstern** [comment]
Thanks @halfbaked and @ahaverty for the suggested improvements.  I have made things more explicit in #1011.

**Comment by halfbaked** [comment]
Changes look good 🖒
