### ISSUE TITLE
Sorting support

### ISSUE THREAD

**Issue by JRSosa** [firebase/FirebaseUI-Android#98]
Passing a "sort by" argument to  the `ListView `or`RecyclerView` `Firebase `adapters

Say I have a list with github repos and in real time of course people are **starring **them, it would be neat if we could sort by "most starred repos"

:+1:

**Comment by raphaelseher** [comment]
You can sort your RecyclerView by passing a Query instead of a normal reference.

```java
Query queryRef = mRef.orderByChild("points");
mAdapter = new FirebaseRecyclerAdapter<Eyesore, EyesoreViewHolder>(Eyesore.class,
            R.layout.eyesore_recycler_item, EyesoreViewHolder.class, queryRef) { ... }
```

**Comment by JRSosa** [comment]
@raphaelseher true, forgot about it.

Thanks :+1:

**Comment by ChanSek** [comment]
I don't think it should be closed. We should have ability to pass some Comparator to sort as per our wish.
As FirebaseArray is an ArrayList, it should be possible. I might want to order ascending or descending.

**Comment by puf** [comment]
The problem is that the re-ordering instructions from Firebase
(onChildChanged, onChildMoved) will not have any knowledge of the local
ordering, so we'll need to local translation layer. Keeping the library
simple and the code small is quite important. So while it is possible to
add this layer to FirebaseArray, I don't feel that would be worth the extra
code at the moment.

If we'd split FirebaseArray into a separate interface and implementation
class, this could be a new implementation class. But I haven't looked at
the impact of that yet.

**Comment by nicholaslie90** [comment]
I might have a case around sorting FirebaseRecyclerAdapter locally: http://stackoverflow.com/questions/40377794/android-client-side-sorting-with-firebaserecycleradapter
